'use strict';
document.addEventListener("DOMContentLoaded", function(event){
  let numberOfItems = 0;
  let num = document.querySelectorAll('li');
  let title = document.querySelector('h1');
  //Alert with number of items in cart on page load
  alert("There are" + " " + num.length + " " + "items in your cart.");

  //Insert html h2 with number of items in cart after h1
  title.insertAdjacentHTML('afterend', '<h2>There are' + ' ' + num.length + ' ' + 'items in your cart</h2>');

  //Function to update cart count:
  function updateCount() {
    document.querySelector('h2').innerHTML = 'There are' + ' ' + document.querySelectorAll('li').length + ' ' + 'items in your cart.';
  }

  let text = document.querySelector('#addToCart');
  let ul = document.querySelector('#cart');
  //Add new items to cart from input field, clear field and update cart count
  document.querySelector('#add').onclick = function() {
    let li = document.createElement('LI'); 
    li.innerHTML = text.value + '<span>&times;</span>';
    let para = document.createElement('P');
    let div = document.querySelector('#div');
    para.innerHTML = text.value;
    para.setAttribute('class', 'paragraph');
    // Insert new html li string at the end of the ul, but not if text form is blank:
    if(text.value == '') {
    } else {
      ul.appendChild(li);
      div.appendChild(para);
      // Clear input form:
      text.value = '';
      // Update h2 with new cart count:
      updateCount();
      updateId();
    }
  }

  //Clear entire cart function
  document.querySelector('#clear').onclick = function() {
    document.querySelector('ul').innerHTML = '';
    updateCount();
    updateId();
  }

  let list = document.querySelectorAll('li');
  let del = document.querySelectorAll('span');
  // loop thru the li array and assign each span an id based on its parent li's position:
  function updateId() { 
    for(var i = 0; i < list.length; i++) {
      del[i].setAttribute('id', i);
  //  delete the ul child node which corresponds with the id number of the span clicked, generated by the above for loop; can't figure out why the onclick event only occurs with two clicks:
      del[i].onclick = function() {
        ul.removeChild(ul.childNodes[this.id]);
        div.removeChild(div.childNodes[this.id]);
        updateCount();
      }
    }
  }
  updateId();
});