$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
    });
    $(document).ready(function(){
    $("#flipp").click(function(){
        $("#panell").slideToggle("slow");
    });
});