var __IntegralASDiagnosticCall = function(){};

try {
	var __IntegralASConfig = {
		jsDoSplit : "false",
		cocaPuffsPath : "",
		debug : "false",
		killPhrases : "",
		jsDiag:'false',
		version:'0',
		mtCell: 10,
		sp_imp_maxLength: 2000,
		sp_imp_jload_maxLength: 2000,
		sp_imp_jsInfo_minLength: 0,
		mtSample: 5,
		cookieDomain:'sc.iasds01.com/dtc',
		trackMouse : "true",
		exchList:{'e1':'nqzryq','e2':'tbbtyrnqf.t.qbhoyrpyvpx','e3':'ehovpbacebwrpg','e4':'chozngvp','e5':'bcrak','e6':'nqoevgr.pbz','e7':'tynz.pbz','e8':'lvryqznantre.pbz','e9':'yvwvg','e10':'nqakf','p11':'ghea.pbz','p12':'zngugnt','p13':'vaivgrzrqvn','p14':'qngnkh','n15':'zrqvn6qrterrf','n16':'dhnagfreir','n17':'esvuho.arg','a18':'napubeserr','a19':'eff2frnepu','a20':'mgfgngvp.pbz','n21':'ovq.npr.nqiregvfvat','e22':'wnfba','v23':'fcbgkpqa','v24':'ogeyy','v25':'yvirenvy','v26':'nqncgi','v27':'nqnc.gi','n29':'qbzqrk.pbz','n30':'ernyih.arg','d31':'cvengronl','d32':'cebklonl','d33':'onlcebkl','d34':'cvengrcebkl','d35':'cebklcvengr','d36':'onlcvengr','n37':'tjnyyrg','p39':'j55p.arg','p40':'c0l.pa','p41':'vcvalbh.pbz','p42':'c0lwferaqre'},
		killFlash: 'false',
		protocol:'https',
		jsref : "http:\/\/tpc.googlesyndication.com\/safeframe\/1-0-2\/html\/container.html",
		asid : "b56566a0-2666-11e6-bf5d-0025904ea250",
		allowViewability : "true",
		jsFeatures : "mousetrack,viewabilityready,consecutive,cachebust:0,forcecocoa:10,rattie,exch,recordalternate:0,cocoapuffs,usedtdomain,nextcocoa:100,bapiDiag,cookie,postDts:0,videotwoseconds,getPl,decodePl,resolution,usetpl,usesca:1,tpiLookupURL,hundredpct,jloadDiag:0,cdnTest:1,blur:0,sendclogs,zeroPing,idMap,offscreen,everySecond:1,sdkdetection,moreAdTalkCalls,slid,fm2:1,largeAd,nextcocoaie:100,usevh,fxdet,mmsb:100,bigmon:0,chromeNativeIO:0,oddet:15",
		adsafeDomain : "adsafeprotected.com:80",
		minimizeCalls : "false",
		adWidth : "300",
		adHeight : "250",
		forceAppend : "false",
		_onInViewMRC15 : __IntegralASConfig && __IntegralASConfig.onInViewMRC15,
		_onAPIResult : __IntegralASConfig && __IntegralASConfig.onAPIResult,
		_onMeasurable : __IntegralASConfig && __IntegralASConfig.onMeasurable,
		_onSuspicious : __IntegralASConfig && __IntegralASConfig.onSuspicious,
		_onInViewMRC : __IntegralASConfig && __IntegralASConfig.onInViewMRC,
		_onInViewMRC5 : __IntegralASConfig && __IntegralASConfig.onInViewMRC5,
		reqquery : "",
		mode : "rjss",
		requrl : "",
		dtBaseURL: "https:\/\/dt.adsafeprotected.com\/dt",
		adsafeSrc : "https:\/\/pixel.adsafeprotected.com\/rfw\/st\/55610\/8683198\/skeleton.js",
		adsafeSep : "?",
		tpiLookupURL:"",
		getTpl: "false",
		use100v: false,
		useBapiCallback: "",
		useViewabilityNotification: "",
		scriptUrl : "https://pixel.adsafeprotected.com/rjss/st/55610/8683198/skeleton.js",
		accountForSadImps:'',
		sendCookie:'true',
		fwMonitoring:'true',
		cdnTestUrl: "//cdn.adsafeprotected.com/cdn-test.js",
		colloTestUrl: "//pixel.adsafeprotected.com/jload?campId=cdnTest&anId=100",
		doNothing: false,
		cdnTestEnabled: false,
		mn: "app08dal",
		cdnTestEnabled: false,
		mobOrTab: false,
		mobFwUrl : "https://mobile.adsafeprotected.com/internal/monitoring/app/initial/55610/8683198/",
		videoId : ''
	};

	if (__IntegralASConfig.jsFeatures.indexOf('asidJsDiagnostic') !== -1) {
		var fakeErr = { message: __IntegralASConfig.asid };
		__IntegralASDiagnosticCall('asid', fakeErr);
	}

	__IntegralASConfig.birthdate = new Date().getTime();
	__IntegralASConfig.useFIF = (!!window.__IntegralASUseFIF) && __IntegralASConfig.mode === 'jload';
	__IntegralASConfig.contextNode = (function() {
		if (__IntegralASConfig.useFIF) {
			return window.frameElement; // Early exit if using FIF
		}
		var tempScript,
			embedded = window != top,
			scripts = document.getElementsByTagName('script'),
			result = scripts[scripts.length - 1],
			scriptIndex = scripts.length,
			useDocWrite = 'jss,jsi,jspix'.indexOf(__IntegralASConfig.mode) !== -1,
			scriptUrl = __IntegralASConfig.scriptUrl;

		try {
			while (--scriptIndex >= 0) {
				tempScript = scripts[scriptIndex];
				if (tempScript.src && tempScript.src.indexOf(scriptUrl) === 0 && tempScript.getAttribute('data-ias-script-tag') === null) {
					result = tempScript;
					tempScript.setAttribute('data-ias-script-tag', 'found');
					break;
				}
			}
			if (scriptIndex === 0 && useDocWrite && !embedded) {
				document.write('<span id="s' + __IntegralASConfig.asid + '"/>');
				result = document.getElementById('s' + __IntegralASConfig.asid).parentNode;
			}
		} catch(e) { }
	
		return result;
	}());

} catch(err) {
	__IntegralASConfig = {};
	__IntegralASDiagnosticCall('bootstrapper', err);
}

__IntegralASConfig.initialize=function(n,t,x){var m,kb=function(){m=new V;var a;m.provide("mobileApp",function(){return a=a||new qa(g)});var c,d,b,e,g=m.provide("features",ra()),k=sa(g),q=ta(),r=ua(m),l=va(),s=wa(),u=new xa(m),w=m.provide("mPage",ya()),B=za(),y=Aa(),D=Ba(),F=Ca(l,D),D=Da(l),E=Ea(l),C=m.provide("browser",Fa()),t=m.provide("intersectionWatcher",Ga(p.getDoc().body)),J=Ha();m.provide("ieXDomainViewability",Ia(C));var K=Ja(C),x=Ka(C),P=v.isVideo()?La(n.videoId,g,y):{};Ma(Na.build());var J=
Oa(J,l,x,K,P,g),z=Pa(J,l,w),A=Qa(r),q=Ra(J,l,g,E,u,C,y,q),L=Sa(l,g,m,r),r=Ta(F,q,l,E,u),G=Ua(F,q),L=Va(L,g),M=Wa(C,q,l,g,x,m,E,K,u,A,w,z,y,P),w=Xa(F,l,g,E,L,u,C,M),y=Ya(m),F=Za(m),E=$a(C,E,M),K=ab(),x=bb();q.setViewabilityMod(M);var Q;if(!function(){var a=!1,b,d;try{f.isDef(n)&&f.isDef(n.killPhrases)&&""!==n.killPhrases&&(b=n.adsafeSrc?n.adsafeSrc:n.requrl+n.reqquery,d=n.killPhrases.split(","),f(d).each(function(c,e){e=decodeURIComponent(d[c]).replace(/^\s+|\s+$/g,"");-1!==b.search(e)&&(a=!0)})),
n.doNothing&&(a=!0)}catch(c){l.add(h.ERROR_CODES.KILL_IT)}return a}()){if(k.isApplicable())try{k.start(),u.addItem(k.getFrameMap(),"fm"),g.on("fm2")&&u.addItem(k.getFrameMapIncludingPeerCase(),"fm2"),g.on("idMap")&&(c=k.getIdMap())&&u.addItem(c,"idMap")}catch(O){l.add(h.ERROR_CODES.ADTALK_GENERAL)}c=cb();c.isApplicable()&&c.start();var N;try{t.isApplicable(C,g,v)&&t.start();"true"!==n.minimizeCalls&&M.init();g.on("mousetrack")&&(e=db(J,u),e.init());N=B.detectTopURL();g.on("exch")&&(d=eb(l,u),d.parse(N));
if(g.on("getPl")&&navigator&&navigator.plugins){b=fb(navigator.plugins);var S=b.hash();u.addItem({output:S.join(".")},"pl",{type:h.DT_CODES.ADTALK});if(g.on("decodePl")&&S.length){var T=b.decode(S);u.addItem({output:T.join(".")},"pd",{type:h.DT_CODES.ADTALK})}}var H=D.getProps();f(H).each(function(a,b){u.addItem({output:b},a,{type:"UFO"})})}catch(R){l.add(h.ERROR_CODES.IMPRESSION_LEADUP)}g.bootstrapOn("use100v")&&gb();q.sendCookie();w.send(N);g.on("cdnTest")&&n.cdnTestEnabled&&F.init();E.isApplicable(g)&&
E.start();g.bootstrapOn("getTpl")&&g.on("usetpl")&&r.init();n.tpiLookupURL&&G.init(n.tpiLookupURL);hb(g);"true"!==n.minimizeCalls&&(Q=(new Date).getTime(),p.execAtEndOfThread(function(){p.execAtEndOfThread(function(){var a={output:(new Date).getTime()-Q};u.addItem(a,"sinceFw",{type:h.DT_CODES.ADTALK});f.isDef(M.readyFired())&&u.addItem({output:M.readyFired()},"readyFired",{type:h.DT_CODES.ADTALK});k.sendAdTalkCall()})}));g.on("usesca")&&y.load()}g.on("fxdet")&&C.hasFlashEnabled()&&!g.bootstrapOn("killFlash")&&
ib(C);s.isApplicable(g,C)&&s.start();K.isApplicable(g)&&K.start();x.isApplicable(g,C)&&x.start();g.on("usevh")&&jb()},f=function(a){var c=function(b){var c=null===a,c="object"===typeof a&&!c,e=!d()&&c;return b?c:e},d=function(){return a instanceof Array},b=function(b,d){if(a.length===+a.length)for(var c=0,e=a.length;c<e;++c)b(c,a[c]);else for(c in a)(a.hasOwnProperty(c)||d)&&b(c,a[c])},e=function(a,d){var c=[];b(function(b,e){var g=a(b,e);if(void 0!==g||d)c[c.length]=g});return c},g=function(a,d){d=
d||",";var c=[];b(function(b,d){var e=a(b,d);f.isDef(e)&&c.push(e)});return c.join(d)},k=function(a,b,d){for(var c in b)f.isDef(b[c])&&(d||b.hasOwnProperty(c))&&(a[c]=b[c]);return a},q=function(a){var d={};b(function(b,e){var g=a(b,e);c(g)&&k(d,g)});return d};return{each:b,isObj:c,isArray:d,invert:function(){return q(function(a,b){var d={};d[b]=a;return d})},mapToObj:q,map:e,keys:function(){var a=[];b(function(b){a.push(b)});return a},toParams:function(a){return g(function(a,b){return"string"===typeof a&&
-1!==a.indexOf("NULL")?b:a+":"+b},a)},stringify:g,toION:function(b,l){var g,k="[",q="]";l=l||0;b=b||{};if(4<++l)return"object";if(!c(!0))return a;d()?g=e(function(a,d){return f(d).toION(b,l)}):(k="{",q="}",g=e(function(a,d){return(b[a]||a)+":"+f(d).toION(b,l)}));return k+g.join(",")+q},compareTo:function(a){var d=!1;b(function(b,c){a[b]!==c&&(d||(d={}),d[b]=c)});return d},mixin:function(b,d){return k(a,b,d)},find:function(a){var d;b(function(b,c){a(b,c)&&(d=c)});return d},findFirst:function(a){var d,
c;b(function(b,e){!c&&a(b,e)&&(d=e,c=!0)});return d},asStrings:function(){var a={};b(function(b,d){a[b]=""+d});return a},selectProperties:function(b){var d={};f(b).each(function(b,c){f.isDef(a[c])&&(d[c]=a[c])});return d},filter:function(a,b){return e(function(b,d){var c;if(f.isUndef(a)||a(b,d))c=d;return c},b)},toArray:function(){return e(function(a,b){return b})},JSONStringify:function(){var b,d,c=!1;t.Prototype&&t.Prototype.Version&&-1===t.Prototype.Version.indexOf("1.7")&&(c=!0);c&&(d=Array.prototype.toJSON,
delete Array.prototype.toJSON);b=JSON.stringify(a);c&&(Array.prototype.toJSON=d);return b}}};f.toBase=function(a,c){var d,b=0>a,e="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),g=[];a=b?-a:a;do d=a%c,g.push(e[d]),a=(a-d)/c;while(0<a);g=g.reverse().join("");return b?"-"+g:g};f.isDef=function(a){return"undefined"!==typeof a};f.isUndef=function(a){return!f.isDef(a)};f.isBool=function(a){return"boolean"===typeof a};f.noop=function(){};f.identity=function(a){return a};f.isFunction=
function(a){return"function"===typeof a};f.isStr=function(a){return"string"===typeof a};f.useIfDef=function(a){return f.isDef(a)?a:!1};f.stringifyTriState=function(a){return!0===a?1:!1===a?0:"na"};f.resolve=function(a){var c=f(arguments).toArray();c.shift();return f.isFunction(a)?a.apply({},c):a};f.flatJSONParse=function(a){var c,d,b,e=/"(\w+)":(\d+|(?:"([^"]*)"))/g,g={};for(b=e.exec(a);b;)c=b[1],d=b[3],b=b[2],g[c]=d||+b,b=e.exec(a);return g};f.debounce=function(a,c){var d;return function(){var b=
this,e=arguments;clearTimeout(d);d=setTimeout(function(){d=null;a.apply(b,e)},c)}};var lb=function(a,c,d,b,e,g,k){var q,r;g=g||b.parentNode||b.parent;var l=function(){if(!q)if(q=v.embedded?a.calcDims():c.calcDims(b,g),e===h.DETECTION_METHODS.VIDEO&&v.embedded){var d=q,l=(new G(b)).getRounded();try{d.set("width",l.width),d.set("height",l.height)}catch(k){m.trigger("error",h.ERROR_CODES.VIDEO_IN_IFRAME_DIMS_CALC)}}else e===h.DETECTION_METHODS.AD_PLACEHOLDER&&q.treatAsPlaceholder();return q},s=function(){var b,
c,g,q;c=n.mobOrTab;f.isUndef(r)&&(b=!c&&(v.friendly||f.isDef(t.mozInnerScreenX))&&k.on("offscreen"),g=l(),c=new G(z.calcWinDims()),b=new G(b?z.calcMonDims():{}),q=e===h.DETECTION_METHODS.VIDEO&&v.embedded?a.getClippedDims():new G({}),r=d.calcPercentInView(g,c,b,q));return r},u=function(){return d.calcInitialViewState(s())},w=function(){return b===t?!1:l().isHidden()};(function(){var a=b===t?x.body:b;A.addEvent(a,"click",function(){m.trigger("adComponentClicked")});A.addEvent(a,"mouseover",function(){m.trigger("adComponentMousedOver")})})();
return{getAdNode:function(){return b},isNode:function(a){return b===a},isHidden:w,isObstructed:function(){return!1},getDims:l,getPercentInView:s,getLocationState:u,getOnPageViewability:function(){return w()?h.OUT_OF_VIEW:u()},getDetectionMethod:function(){return e},getContainerDims:function(){return G(g)},refresh:function(){r=q=void 0;var a,d=b.parentNode;if(d){for(;b!==t&&d&&d!==x&&!a;)a=d===g,d=d.parentNode;a||(g=b.parentNode)}}}},mb=function(a,c,d,b){var e=[],g=function(){return e[0]&&e[0].getDetectionMethod()===
h.DETECTION_METHODS.AD_PLACEHOLDER},k=function(l,k,f){var r=g()||0===e.length;l=lb(a,c,d,l,k,f,b);r&&k!==h.DETECTION_METHODS.AD_PLACEHOLDER&&m.trigger("primaryadfound",l);g()&&e.shift();e.push(l)},q=function(){var a,b=!0,d=0,c=0;f(e).each(function(e,l){var g;g=l.getDims();g.hasValidDims()&&(a=l.getPercentInView(),a===h.NA&&(b=!1),g=g.area(),d+=g,c+=a/100*g)});return{totalArea:d,totalInView:c,hasMeasurement:b}},r=function(){var a=q();return a.hasMeasurement?p.round(a.totalInView/a.totalArea*100):h.PIV_NA},
l=function(){var a=q().totalArea>=h.MRC_LARGE_AD_SIZE&&b.on("largeAd")&&!v.isVideo();return d.calcInitialViewState(r(),!1,a)},s=function(a){var b=-1;f(e).each(function(d,c){c.isNode(a)&&(b=d)});return b},u=function(a){return function(){return e[0]&&e[0][a]()}};m.on("adComponentAdded",function(a){f(a).each(function(a,b){-1===s(b)&&k(b,h.DETECTION_METHODS.MUTATION)})});m.on("adComponentRemoved",function(a){f(a).each(function(a,b){var d=s(b);-1<d&&e.splice(d,1)})});return{getOriginatingNode:u("getAdNode"),
getDims:u("getDims"),isObstructed:u("isObstructed"),getDetectionMethod:u("getDetectionMethod"),getContainerDims:u("getContainerDims"),getViewState:l,getPercentInView:r,isHidden:u("isHidden"),isUsingPlaceholder:g,hasAd:function(){return!!e.length},refresh:function(){f(e).each(function(a,b){b.refresh()})},addAdComponent:k,getOutOfViewReasons:function(){var a=[],b=e[0],d=h.OUT_OF_VIEW_REASONS,c=l();c!==h.OUT_OF_VIEW&&c!==h.PARTIAL_VIEW_MINUS||a.push(d.GEOM);b.isHidden()&&a.push(d.HIDDEN);b.isObstructed()&&
a.push(d.OBSTRUCTION);return a},getComponentCount:function(){return e.length}}},nb=function(a){var c=!1;if(!f.isUndef(t.MutationObserver)){var d=new MutationObserver(function(a){p.execAtEndOfThread(function(){c&&f(a).each(function(a,b){b.addedNodes.length&&m.trigger("adComponentAdded",b.addedNodes);b.removedNodes.length&&m.trigger("adComponentRemoved",b.removedNodes)})})}),b=function(){c=!0;setTimeout(function(){c=!1},40)};m.on("adComponentClicked",b);m.on("adComponentMousedOver",b);try{d.observe(x.body,
{attributes:!0,childList:!0,characterData:!0})}catch(e){a.add(h.ERROR_CODES.AC_WATCHER)}}},gb=function(){var a,c,d=!1,b=m.request("mPage"),e=function(){!d&&c&&a&&!b.isHidden()&&(d=!0,m.trigger("sendDt",h.DT_CODES.LARGE_BILLABLE))};m.on("primaryadfound",function(b){a=b.getDims().area()>=h.MRC_LARGE_AD_SIZE;e()});m.on("impressionsent",function(){c=!0;e()});b.onHiddenChange(e)},ta=function(){var a=[],c={},d={percentInView:"piv",sl:"vs",reason:"r",width:"w",height:"h"};m.on("newScreenEvent",function(b){b=
f(b).selectProperties(f(d).keys());b=f(b).asStrings();var e=f(b).compareTo(c);e&&(e.t=v.getTagTime(),a.push(e));f(c).mixin(b)});return{toString:function(){return f(a).toION(d)}}},ob=function(a,c,d,b,e,g,k){var q;(function(){var g=d.getRounded(),l=g.width-5,f=g.height-5,u=0.5*g.width+1,g=0.5*g.height+1;q=[new a(c,l,f,e,k,b),new a(c,l,5,e,k,b),new a(c,5,f,e,k,b),new a(c,5,5,e,k,b),new a(c,u,g,e,k,b)]})();return{getNumInView:function(){var a=[],b=0;f(q).each(function(b,d){var c=d.isInView()?1:0;a.push(c)});
g.addItem({output:a.join(".")},"pvs");f(a).each(function(a,d){b+=d});return b},getPctInView:function(a){return 5===a?100:3<=a?51:0},isReady:function(){var a=!0;f(q).each(function(b,d){d.isNotReadyToReport()&&(a=!1)});return a},remove:function(){f(q).each(function(a,b){try{b.remove()}catch(d){}})}}},pb=function(a,c,d,b,e,g,k,q){var r=e.on("nextcocoa")?la:ma,l=new a(r,x.body,c,b,e,k,q),s,u,w=0;d=d||f.noop;s=setInterval(function(){l.isReady()&&!u?(u=!0,d(),clearInterval(s)):(5===++w||u)&&clearInterval(s)},
50);return{checkViewable:function(){var a=l.isReady(),b=l.getNumInView(),b=l.getPctInView(b),c=g.calcInitialViewState(b,!0);a&&!u&&(u=!0,d());return{str:a?c:h.NA,pct:a?b:-1}},removePixels:function(){l.remove()}}},fa=function(a,c,d,b,e,g){var k,q,r=c.getRounded(),l=[],s=!1,u=0,w=b.on("largeAd")&&c.isMrcLarge()&&!v.isVideo()?qb(r):rb(r),B=function(){var a;if(!s)for(s=!0,a=0;a<l.length;a++)if(l[a].isNotReadyToReport()){s=!1;break}return s},y=function(){var a=0;f(l).each(function(b,d){d.isInView()&&(a+=
1)});return w.getPctInView(a)};(function(){var d=w.get();f(d).each(function(d,c){var k=new a(x.body,c.x,c.y,b,e,g);k.weight=c.weight;l.push(k)})})();d=d||f.noop;k=setInterval(function(){B()&&!q?(q=!0,d(),clearInterval(k)):(5===++u||q)&&clearInterval(k)},50);return{checkViewable:function(){var a=B(),e;a&&(e=b.on("largeAd")&&c.isMrcLarge()?30:50,e=y()>=e?h.IN_VIEW:h.OUT_OF_VIEW);a&&!q&&(q=!0,d());return{str:a?e:h.NA,pct:a?y():-1}},removePixels:function(){f(l).each(function(a,b){try{b.remove()}catch(d){}})}}},
V=function(){var a=new sb,c=new tb;return f(a).mixin(c)},tb=function(){var a={},c=function(d,b){a[d]=a[d]||new X;a[d].push(b)};return{on:function(a,b){b?c(a,b):f(a).each(c)},trigger:function(d){var b,c=f(arguments).toArray();if(b=a[d])c.shift(),b.run.apply({},c)}}},cb=function(){var a,c={},d={ox:0},b=p.getWindow(),e=f.isDef(b.JSON)&&f.isDef(b.postMessage),g=function(a){var b=a.uniqueId;a=d[a.vendorKey];var e=!1;f.isDef(a)&&1>a&&b&&!c[b]&&(e=!0);return e},k=function(){if(a)return a.type="receipt",
a},q=function(b,e,g){a=e;d[e.vendorKey]++;g();c[e.uniqueId]=!0;r(e)&&(g="false"===e.isSampling,b=["ext",e.vendorKey,e.dataKey].join("_"),g={encode:!0,minDt:g,type:g?h.DT_CODES.EXTERNAL:h.DT_CODES.UNLOAD},m.trigger("addOutputItem",{output:e.dataValue},b,g),m.trigger("addOutputItem",{output:e.vendorKey},"ext_vendor",g),"false"===e.isSampling&&m.trigger("sendMinDt",h.DT_CODES.EXTERNAL))},r=function(a){var b=function(a){return f.isStr(a)&&50>a.length};return b(a.vendorKey)&&b(a.dataKey)&&b(a.dataValue)};
return{isApplicable:function(){return e},start:function(){(new W).listen(g,q,k)}}},U=function(a,c,d,b){var e=m.request("browser");if(m.request("features").bootstrapOn("killFlash"))return{style:{},isPlaceholder:!0};var g=function(a,b){return'<param name="'+a+'" value="'+b+'"/>'};return function(){var k,f,r,l=n.dtBaseURL,s=n.cocaPuffsPath,l=new O(l);l.sub(c||"static");l.master(l.master().split(":")[0]);l.path("");s&&(l.master(s),l.sub(""));l+=a;s=g("allowscriptaccess","always");k=g("movie",l)+g("play",
"true")+g("loop","true");r=e.browserIs(h.BROWSERS.IE)||e.browserIs(h.BROWSERS.MSEDGE);f=e.browserIs(h.BROWSERS.IE);r&&(r=b?"window":"transparent",k+=g("wmode",r));d&&(s+=g("FlashVars",d));f?(f=x.createElement("div"),r="blag"+n.birthdate+p.random(),f.innerHTML="<object "+('id="'+r+'" ')+'classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" '+('type="'+h.FLASH_MIME+'" ')+('data="'+l+'" ')+">"+k+s+"</object>",k=f.firstChild):(k=x.createElement("object"),k.data=l,k.type=h.FLASH_MIME,k.innerHTML=s);l=
k;l.style.position="absolute";l.style.width="1px";l.style.opacity="0";l.style.height="0px";return k}()},la=function(a,c,d,b,e,g,k,q){var r=g.browserIs(h.BROWSERS.IE)||g.browserIs(h.BROWSERS.MSEDGE),l="_IASflashPixelCallback"+(n.birthdate+""+p.round(1E6*p.random())),s=!1,u=!1,w,B,y,D,F=function(){if(w&&f.isFunction(w.jsHandshake)&&!s){w.style.height="1px"===w.style.height?"2px":"1px";try{w.confirmResize()}catch(a){s=!0,m.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}}},E=function(){if(s)return!1;
var a,b;try{(a=D||w&&f.isFunction(w.jsHandshake))&&!u&&(D=!0,t[l]=C,b=w.jsHandshake(l),u=!0,C(b))}catch(d){a=!1,s=!0,m.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}return a},C=function(a){try{if(f.isUndef(a.isInView))throw"corrupted Flash pixel message received";y=1===+a.isInView}catch(b){m.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}},I=function(a,b,d){var c=new U(r?"/detector_4_5_IE.pix":"/detector_4_5.pix"),e=c.style;c[h.IAS_DETECTOR]="true";e.left=b+"px";e.top=d+"px";c.isPlaceholder||a.appendChild(c);
e.height="1px";w=c;r&&!c.isPlaceholder&&setInterval(F,100);return c}(a,c,d);return{isInView:function(){var a;if(E()){try{a=y}catch(b){D=!1,m.trigger("error",h.ERROR_CODES.COCOA_GONE)}g.browserIs("w")&&void 0!==a&&(w.style.height=B?"1px":"2px",B=!B)}return E()&&a},isNotReadyToReport:function(){return!E()},createdFlash:w,remove:function(){I.parentNode&&I.parentNode.removeChild(I)}}},ma=function(a,c,d,b,e,g,k){var q=g.browserIs(h.BROWSERS.IE)||g.browserIs(h.BROWSERS.MSEDGE),r=!1,l,s,u,w,B,y=function(a,
b){return'<param name="'+a+'" value="'+b+'"/>'},D=function(a,b){return a+'="'+b+'" '},F=function(){if(E()&&!r){l.style.height="1px"===l.style.height?"2px":"1px";try{l.confirmResize()}catch(a){r=!0,m.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}}},E=function(){var a=!1;try{a=l&&f.isFunction(l.jsHandshake)}catch(b){}return a},C=function(){if(r)return!1;var a;try{if((a=B||E())&&!u){B=!0;var b=f.flatJSONParse(l.jsHandshake());u=b.id;if(f.isUndef(u))throw"corrupted Flash pixel message received";w=1===
+b.isInView}}catch(d){a=!1,r=!0,m.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}return a};A.addEvent(t,"message",function(a){try{var b=f.flatJSONParse(a.data);"IASCOCOA"===b.type&&b.id===u&&(w=1===+b.isInView)}catch(d){m.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}});var I=function(a,b,d){var c;c=new O;var e=n.cocaPuffsPath;c.sub("static");c.master(c.master().split(":")[0]);e&&(c.master(e),c.sub(""));var e=c+(q?"/detector_4_2_IE.pix":"/detector_4_1.pix"),k=y("allowscriptaccess","always"),f=
y("movie",e)+y("play","true")+y("loop","true");q&&(f+=y("wmode","transparent"));g.browserIs(h.BROWSERS.IE)?(c=x.createElement("div"),c.innerHTML="<object "+D("id","blag"+n.birthdate+p.random())+D("classid","clsid:D27CDB6E-AE6D-11cf-96B8-444553540000")+D(h.IAS_DETECTOR,"true")+D("type",h.FLASH_MIME)+D("data",e)+">"+f+k+"</object>",l=c.firstChild):(l=x.createElement("object"),l.data=e,l.type=h.FLASH_MIME,l.innerHTML=k,l[h.IAS_DETECTOR]="true");l.style.position="absolute";l.style.width="1px";l.style.opacity=
"0";l.style.height="0px";c=l;e=c.style;e.left=b+"px";e.top=d+"px";a.appendChild(c);e.height="1px";q&&setInterval(F,100);return c}(a,c,d);return{isInView:function(){var a;if(C()){try{a=w}catch(b){B=!1,m.trigger("error",h.ERROR_CODES.COCOA_GONE)}g.browserIs("w")&&void 0!==a&&(l.style.height=s?"1px":"2px",s=!s)}return C()&&a},isNotReadyToReport:function(){return!C()},createdFlash:l,remove:function(){I.parentNode&&I.parentNode.removeChild(I)}}},Y=function(){var a=function(d,b,c){var g=b.length,k=d.frames;
c&&c(d,b);if(k.length){for(d=0;d<k.length;d++)b[g]=d,a(k[d],b,c);b.pop()}},c=function(d){a(top,[0],d)};return{traverse:c,getFrames:function(a){var b=[];c(function(a){b.push(a)});return f(b).filter(a)}}},X=function(){var a=[];return{push:function(c){a[a.length]=c},run:function(){var c=arguments;f(a).each(function(a,b){b.apply({},c)})}}},ga=function(a){return{doEligibleJobs:function(c){var d=a[0],b=d&&d.time;b&&c>=b&&(d.task(),a.shift())},getNextJob:function(){return a[0]}}},W=function(){var a=function(a,
d,b,e){var g,k=f.noop,q,r;if(JSON&&JSON.parse)try{g=JSON.parse(a.data),q=a.source,d(g)&&(e&&(r=e(q))&&(k=function(){(new Z(q)).send(function(){return r})}),b(a,g,k))}catch(l){g&&m.trigger("error",h.ERROR_CODES.MESSAGE_LISTENER)}};return{listen:function(c,d,b){A.addEvent(t,"message",function(e){a(e,c,d,b)})}}},Z=function(a){var c=function(a){return f(a).mapToObj(function(a,d){var c;f.isFunction(d)||(c={},c[a]=d);return c})};return{send:function(d){if(JSON&&JSON.stringify){var b=f(a).isObj()?[a]:(new Y).getFrames(a);
f(b).each(function(a,b){var k;k=f.resolve(d,b)||{};k.sentTime=p.now();k=c(k);b.postMessage(f(k).JSONStringify(),"*")})}}}},xa=function(a){var c=0,d={},b=function(a,b,d){if(f.isUndef(a.output))throw Error("item with id "+b+' must have "output" method');this.item=a;this.id=b||++c;this.props=d||{};this.output=function(){return f.isFunction(a.output)?a.output():a.output}},e=function(a){var b,c,e=[];for(b in d)d.hasOwnProperty(b)&&(c=a(b,d[b]))&&e.push(c);return e},g=function(a,c,e){e=e||c;e="string"!==
typeof e?e:{};var g=function(a,c,e){a=new b(a,c,e);d[a.id]=a};f(a.output).isObj()?f(a.output).each(function(a,b){g({output:b},a,e)}):g(a,c,e)};a.on("addOutputItem",function(a,b,d){g(a,b,d)});return{addItem:g,filterOutput:function(a,b){return e(function(d,c){var e=c.props,g=c.output();a(e)&&(e.encode?b[encodeURIComponent(d)]=encodeURIComponent(g):b[d]=g)})},iterate:e,getItem:function(a){return d[a]}}},qb=function(a){var c=a.width-5,d=a.height-5,b=0.5*a.width+1,e=0.5*a.height+1,g=0.3*a.width+1,f=0.7*
a.width+1,q=0.3*a.height+1,r=0.7*a.height+2,l,s=function(b,d){1>b&&(b=1);1>d&&(d=1);b>a.width&&(b=0!==a.width?a.width:1);d>a.height&&(d=0!==a.height?a.height:1);return{x:p.floor(b),y:p.floor(d)}};l=[s(c,d),s(c,5),s(5,d),s(5,5),s(b,e),s(g,q),s(f,q),s(g,r),s(f,r)];return{get:function(){return l},getPctInView:function(a){var b;0===a?b=0:1===a?b=10:2===a?b=20:5>a?b=30:7>a?b=50:9>a?b=70:9===a&&(b=100);return b}}},rb=function(a,c){var d=0.5*a.width+1,b;b=[{y:p.floor(0.5*a.height+1),x:p.floor(d)}];return{get:function(){return b},
getPctInView:function(a){return 1===a?50:0}}},sb=function(){var a={},c=function(d,b){a[d]=b};return{request:function(d){var b,c=a[d],g=f(arguments).toArray();g.shift();f.isUndef(c)||(b=f.isFunction(c)?c.apply({},g):c);return b},provide:function(d,b){b?a[d]=b:f(d).each(c);return b}}},Pa=function(a,c,d){return{collect:function(){var b=a.find(),c=b.getOutOfViewReasons(),g=d.isHidden(),k=G(z.calcWinDims()),q=b.getDims();if(!k.hasValidDims()||!q.hasValidDims())return{viewState:h.NA,posViewState:h.NA,embedded:v.embedded,
winDimensions:k,adDimensions:q};!0===g&&c.push(h.OUT_OF_VIEW_REASONS.FOCUS);return{winDimensions:k,adDimensions:q,containerDimensions:b.getContainerDims(),method:b.getDetectionMethod(),viewState:c.length?h.OUT_OF_VIEW:b.getViewState(),percentInView:b.getPercentInView(),reason:c.join("."),obstructed:f.stringifyTriState(b.isObstructed()),isHidden:f.stringifyTriState(b.isHidden()),tabHidden:f.stringifyTriState(g),posViewState:b.getViewState(),adCompCount:b.getComponentCount()}}}},ub=function(a){a=a||
f.identity;var c=[],d=p.now(),b=function(){var a=p.now();c.length&&(c[c.length-1].duration+=a-d,d=a)};return{clear:function(){b();c=[]},fastForward:b,get:function(){return c},hasAlwaysBeen:function(a){return 1===c.length&&c[0].state===a},addState:function(d){var g=c[c.length-1];d=a(d);b();0!==c.length&&d===g.state||c.push({state:d,duration:0})}}},vb=function(a){var c=a||1,d=0,b=0,e=0,g=0;return{start:function(){0===d%c&&(e=p.now())},stop:function(){0===d%c&&(g+=p.now()-e,b++);d++},getTime:function(){return g},
getCount:function(){return b}}},ha=function(a){var c=0,d=v.getTagTime(),b=0,e,g;return{getTotalTime:function(){return b},stop:function(){c=0;d=v.getTagTime()},mark:function(){e=v.getTagTime()-d;c+=e;c>a&&(g=c-e<a,b+=g?c:e);d=v.getTagTime()}}},O=function(a){var c=/((http|https):\/\/(([^\/\.]*)\.([^\/]*)))(?:\/(.[^?]*))*/.exec(a||n.adsafeSrc||n.requrl),d=c[2],b=c[4],e=c[5],g=a?c[6]:"",k,q=function(a){f.isDef(a)&&(b=a);return b},r=function(a){f.isDef(a)&&(e=a);return e},l=function(){var a="";f(k).each(function(b,
d){a+="&"+b+"=";a=f(d).isObj()?a+("{"+f(d).toParams()+"}"):a+d});return"?"+a.substr(1)};return{fullDom:c[1],sub:q,master:r,setParam:function(a,b){k=k||{};k[a]=k[a]||{};f(b).isObj()?f(k[a]).mixin(b):k[a]=b},path:function(a){g=a},_getQsParams:function(){return k},toString:function(){var a=q()?q()+".":"",b=g?"/"+g:"",c=k?l():"";return d+"://"+a+r()+b+c}}},Oa=function(a,c,d,b,e,g){var f=-1!==n.mode.indexOf("jsvid"),q=n.contextNode.parentNode,r=m.request("mobileApp"),l=mb(b,a,d,g);nb(c);return{find:function(){var a,
b=h.DETECTION_METHODS,d=function(d){var c=z.findChildWithLargestContent(q);1<z.getNodeArea(c)&&!c[h.IAS_DETECTOR]?l.addAdComponent(c,d||b.AD_HUNT,q):l.hasAd()||(a=z.getPlaceholderSpan(),q.insertBefore(a,n.contextNode.nextSibling),l.addAdComponent(a,d||b.AD_PLACEHOLDER))};l.isUsingPlaceholder()||!l.hasAd()?r.isMobileAppEnvironment()?d(r.getDetectionMethod()):f?l.addAdComponent(e.findAdNode(),b.VIDEO):v.embedded?l.addAdComponent(t,b.IFRAME):d():l.refresh();return l},getDetectionMethod:function(){},
isAdDetected:function(){return!0!==l.isUsingPlaceholder()},getOriginatingElement:function(){return l.getOriginatingNode()},getParent:function(){return q}}},hb=function(a){var c=function(a,b){var c;b&&b.id&&(c=b.id.replace(/[^\w-_\/]/g,""));return c};(function(){var d;try{if("jload"===n.mode&&a.on("slid")&&v.friendly&&!v.isMobileApp()){var b,e;if(b=z.getOurNodeInTop()){var g=z.getAncestorNodes(b);e=f(g).map(c)}(d=e=e&&f(e).toION())&&m.trigger("addOutputItem",{output:d},"slid",{type:h.DT_CODES.ADTALK})}}catch(k){m.trigger("error",
h.ERROR_CODES.AD_SLOT_ID)}})()},Ta=function(a,c,d,b,e){var g=function(a,b,d){e.addItem({output:a+"."+b+"."+d},"ctpl")},k=function(e){try{c.diagnostic("c");var k=e.length,l=0,s=0;g(k,0,0);f(e).each(function(d,c){a.send(c.replace("%%CBS%%",b.getCacheBustId()),function(){g(k,l,++s)},!0);g(k,++l,s)})}catch(u){d.add(h.ERROR_CODES.AT_SEND)}};return{init:function(){try{var b=(new O).fullDom;"/"!==b.slice(-1)&&(b+="/");b+="tpl?asId="+n.asid;a.jsonp(b,k)}catch(c){d.add(h.ERROR_CODES.AT_INIT)}}}},Sa=function(a,
c,d,b){return{enabled:"true"===n.useBapiCallback,callback:function(c){d.trigger("sendDiag");try{"true"===n.accountForSadImps&&b.measure(c),n._onAPIResult&&n._onAPIResult(c)}catch(g){a.add(h.ERROR_CODES.BAPI_CALLBACK),d.trigger("sendDiag","bapiClient")}}}},Fa=function(){var a=h.BROWSERS,c,d=function(){var a="0",b=p.getWindow(),d=function(a){return a.replace(/\D+/g,",").match(/^,?(.+),?$/)[1].split(",").join(".")};try{try{var c=p.getNewActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{c.AllowScriptAccess=
"always"}catch(e){a="6"}}catch(g){}a=d(p.getNewActiveXObject("ShockwaveFlash.ShockwaveFlash").GetVariable("$version"))}catch(f){try{b.navigator.mimeTypes[h.FLASH_MIME].enabledPlugin&&(a=d((b.navigator.plugins["Shockwave Flash 2.0"]||b.navigator.plugins["Shockwave Flash"]).description))}catch(k){}}return a},b=function(){f.isUndef(c)&&(c=d());return c},e=function(a){return k()===a},g=function(){var a=p.getDoc();return a&&a.documentMode?a.documentMode:h.NA},k=function(){var b="u",d=p.getWindow();try{f.isDef(d.opera)&&
f.isDef(d.opera.buildNumber)?b=a.OPERA:f.isDef(d.mozInnerScreenY)?b=a.GECKO:f.isDef(d.chrome)&&f.isDef(d.chrome.csi)?b=a.CHROME:f.isDef(d.msWriteProfilerMark)&&f.isDef(d.crypto)?b=a.MSEDGE:f.isDef(d.attachEvent)||f.isDef(d.msCrypto)?b=a.IE:f.isDef(d.WebKitPoint)&&(b=a.WEBKIT)}catch(c){}return b},q=function(){var b=["{45EA75A0-A269-11D1-B5BF-0000F8051515}","{3AF36230-A269-11D1-B5BF-0000F8051515}","{89820200-ECBD-11CF-8B85-00AA005B4383}"],d=h.NA,c=p.getDoc(),g=c.createElement("div");if(e(a.IE))try{if("-ms-ime-align"in
c.documentElement.style)d="11";else for(g.style.behavior="url(#default#clientcaps)",c=0;c<b.length&&!(d=g.getComponentVersion(b[c],"componentid").replace(/,/g,"."));c++);}catch(f){}return d};return{browserIs:e,hasIntersectionObserver:function(){return"function"===typeof IntersectionObserver},hasFlashEnabled:function(){return"0"!==b()},getFlashVersion:b,getDocumentMode:g,getBrowserType:k,getUserAgent:function(){var a=!1,b=p.getWindow();f.isDef(b.navigator)&&f.isDef(b.navigator.userAgent)&&(a=b.navigator.userAgent);
return a},isOnWin7:function(){return 0<p.getWindow().navigator.userAgent.indexOf("Windows NT 6.1")},isIEVersion:function(a){return 0===q().indexOf(a)},params:function(){var d=k(),c=b(),s;s=5;var u=p.getWindow(),w=p.getDoc();e(a.IE)?u.msCrypto?s=11:u.atob?s=10:u.addEventListener?s=9:u.JSON&&w.querySelector?s=8:u.XMLHttpRequest?s=7:w.compatMode&&(s=6):s=h.NA;var u=g(),w=q(),B=h.NA,y=p.getWindow();f.isDef(y.navigator)&&f.isDef(y.navigator.appName)&&(B=y.navigator.appName.toLowerCase()[0]);return{br:d,
fv:c,bv:s,dm:u,abv:w,an:B}}}},Za=function(a){var c=0.5<=p.random()?"cdn":"collo",d=function(){a.trigger("sendDiag",c+"Test","cdnTest")};return{init:function(){var b,e=n[c+"TestUrl"];e&&(b=-1===e.indexOf("?")?"?":"&",e=e+b+"asid="+n.asid,a.trigger("exec",e,d))}}},Ca=function(a,c){var d=function(a,b){var d,c,e=n.contextNode.parentNode;b=b||a;a=1<arguments.length?a:"script";d={script:['<script type="text/javascript" src="','">\x3c/script>'],iframe:['<iframe width="100%" height="100%" frameborder="0" vspace="0" hspace="0" scrolling="no" marginheight="0" marginwidth="0" src="',
'"></iframe>'],img:['<img src="','"/>']}[a];c=d[0]+b+d[1];"true"===n.forceAppend?"script"!==a?(d=x.createElement("DIV"),d.innerHTML=c,e.appendChild(d.childNodes[0])):(d=x.createElement("SCRIPT"),d.src=b,e.appendChild(d)):x.write(c)},b=function(a,b,d){var c=!d&&A.getXHR2();c?(c.open("POST",a),c.onreadystatechange=function(){4===c.readyState&&200===c.status&&b&&b()},c.send()):(d=z.createImage(),b&&(d.onload=b),d.src=a)},e=function(a,b){var d=x.createElement("script");d.type="text/javascript";d.src=
a;b&&(d.onload=b);f.isDef(n.contextNode.parentNode)&&n.contextNode.parentNode.appendChild(d)},g=function(d){f.isFunction(d)?d():"string"===typeof d?b(d,void 0,!0):a.add(h.ERROR_CODES.NOTIFY_CLIENT)},k=function(a,b,d,g){e(c.wrap(a,b,d,g))};m.on({addNode:d,send:b,exec:e,notify:g,jsonp:k});return{addNode:d,send:b,exec:e,notify:g,jsonp:k}},h={MRC_LARGE_AD_SIZE:242500,FLASH_MIME:"application/x-shockwave-flash",IN_VIEW:"inView",OUT_OF_VIEW:"outOfView",PARTIAL_VIEW_PLUS:"partialViewPlus",PARTIAL_VIEW_MINUS:"partialViewMinus",
NA:"na",PIV_NA:-1,DT_CODES:{ADTALK:"a",DIAGNOSTIC:"b",PERFORMANCE:"e",THIRD_PARTY:"i",LARGE_BILLABLE:"l",VIDEO_EVENTS:"m",PING:"p",FULLY_INVIEW:"pf",QUARTILE_FULLY_INVIEW:"qf",SCA:"s",POS_INVIEW:"t",UNLOAD:"u",VIEWABILITY_READY:"v",VH:"vh",EXTERNAL:"x"},DETECTION_METHODS:{AD_PLACEHOLDER:"s",AD_HUNT:"a",IFRAME:"i",VIDEO:"v",MRAID:"m",AVID:"av",MUTATION:"c"},OUT_OF_VIEW_REASONS:{GEOM:"l",OBSTRUCTION:"o",FOCUS:"f",COLLAPSED:"c",HIDDEN:"h",VIDEO:"v"},VIDEO_CHANNELS:{VANS:{AS3_ADAPTOR:"av3",JS_ADAPTOR:"jv3"}},
PERF_TRACKER_TYPES:{VANS:{TYPE:"vans",COUNT:4},JSVIDWRAPPER:"jsvidwrap",ASVIDWRAPPER:"asvidwrap"},ERROR_CODES:{GET_AD_DIMENSIONS:"a",AD_SLOT_ID:"A",BAPI_CALLBACK:"b",ADTALK_GENERAL:"c",COCOA_GONE:"C",GET_SCREEN_LOC_GET_DIMENSIONS:"d",ADTALK_DUBIOUS:"D",NO_CONTAINER:"e",VIDEO_IN_IFRAME_DIMS_CALC:"F",PHONE_HOME:"h",UID_GENERATION:"i",IMPRESSION_URLS:"I",JSINFO:"J",KILL_IT:"k",LOCATION_DETAILS:"l",IMPRESSION_LEADUP:"L",MESSAGE_LISTENER:"m",NOTIFY_CLIENT:"n",AT_INIT:"N",OFF_DESKTOP:"O",GET_SCREEN_LOC_PIV_CALC:"p",
PLUGIN_PARSING:"P",GET_ELEM_STYLE:"s",AT_SEND:"S",NO_VIDEO_AD_INTERFACE:"u",ENVIRONMENT:"v",GET_WIN_DIMENSIONS:"w",AC_WATCHER:"W",EXCHANGE_PARSING:"x",CHECK_SCREEN_LOC:"V",MOBILE_APP:"M",FLASH_API_ACCESS:"z"},IAS_DETECTOR:"iasdetector",BROWSERS:{WEBKIT:"w",OPERA:"o",GECKO:"g",CHROME:"c",IE:"i",MSEDGE:"e"}},v=function(){var a=t!=top,c=function(){var a;try{a=!!top.document}catch(b){a=!1}return a}();return{embedded:a,friendly:c,friendlyIframe:a&&c,xDomainIframe:a&&!c,getTagTime:function(){return p.now()-
n.birthdate},getPageTime:function(){return f.isDef(t.chrome)&&f.isDef(t.chrome.csi)&&f.isFunction(t.chrome.csi)?p.round(chrome.csi().pageT):h.NA},isVideo:function(){return-1!==n.mode.indexOf("jsvid")},isMobileApp:function(){return f.isDef(t.mraid)}}}(),A={addEvent:function(a,c,d,b){f.isDef(a.addEventListener)?"mouseenter"===c?a.addEventListener("mouseover",A.mouseEnter(d),b):"mouseleave"===c?a.addEventListener("mouseout",A.mouseEnter(d),b):a.addEventListener(c,d,b):f.isDef(a.attachEvent)&&a.attachEvent("on"+
c,d)},removeEvent:function(a,c,d){f.isDef(a.removeEventListener)?("mouseenter"===c?(c="mouseover",d=A.mouseEnter):"mouseleave"===c&&(c="mouseout",d=A.mouseEnter),a.removeEventListener(c,d)):f.isDef(a.detachEvent)&&a.detachEvent("on"+c,d)},mouseEnter:function(a){var c=this;return function(d){var b=d.relatedTarget;this===b||c.isAChildOf(this,b)||a.call(this,d)}},isAChildOf:function(a,c){if(a===c)return!1;for(;c&&c!==a;)c=c.parentNode;return c===a},getStyle:function(a,c){var d="";x.defaultView&&x.defaultView.getComputedStyle?
d=x.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(c=c.replace(/\-(\w)/g,function(a,d){return d.toUpperCase()}),d=a.currentStyle[c]);return d},getXHR2:function(a,c){var d,b;f.isDef(t.XMLHttpRequest)?(b=new XMLHttpRequest,"withCredentials"in b&&(d=b)):f.isDef(XDomainRequest)&&(d=new XDomainRequest);return d}},Ra=function(a,c,d,b,e,g,k,q){var r=0,l=0,s=!1,u,w={},B=[h.DT_CODES.ADTALK],y=function(a,c,e,g,q,u){e=e||!d.on("postDts");var y=a===h.DT_CODES.VH||a===h.DT_CODES.DIAGNOSTIC||
a===h.DT_CODES.ADTALK;if(b.impressionIsIdentifiable()&&(y||"n"!==k.getCurrentLoc()))try{var B=n.dtBaseURL,D=new O(B),t=p.now(),v=w[a];B||(D.path("dt"),d.on("usedtdomain")&&D.sub("dt"));a===h.DT_CODES.PERFORMANCE&&D.sub("dtias");F(D,a,c);q&&q.field&&D.setParam(q.field,q.value);g||E(D,a);m.trigger("send",D,function(){l+=1;r=p.now()-t;f.isFunction(u)&&u()},e);a===h.DT_CODES.UNLOAD&&(s=!0);w[a]=f.isDef(v)?v+1:1}catch(x){__IntegralASDiagnosticCall("dt-"+a,x),m.trigger("error",h.ERROR_CODES.PHONE_HOME)}};
a=function(a,b){var c={bapi:"a",bapiClient:"b",jload:"c",jss:"d",jsi:"e",cdnTest:"f",colloTest:"g"},e=n.mode,c=c[a]||c[e];d.on(b||e+"Diag")&&c&&y(h.DT_CODES.DIAGNOSTIC,-5,!0,!0,{field:"bkp",value:c})};var D=function(a){var b;a===h.DT_CODES.UNLOAD?b=-1:a===h.DT_CODES.ADTALK?b=-2:a===h.DT_CODES.VIEWABILITY_READY?b=-3:a===h.DT_CODES.VIDEO_EVENTS?b=-4:a===h.DT_CODES.DIAGNOSTIC?b=-5:a===h.DT_CODES.THIRD_PARTY?b=-6:a===h.DT_CODES.QUARTILE_FULLY_INVIEW?b=-7:a===h.DT_CODES.LARGE_BILLABLE&&(b=-8);var d=w[a];
f.isDef(d)&&-1!==B.indexOf(a)&&0!==d&&(b=b+"."+d);return b},F=function(a,d,c){c=f.isDef(c)?c:D(d);a.setParam("asId",n.asid);c={c:b.getCacheBustId(),pingTime:c,time:v.getTagTime(),type:d};e.filterOutput(function(a){return a.minDt&&(!a.type||a.type===d)},c);a.setParam("tv",c)},E=function(a,b){var f,s={};k.fastForward();b===h.DT_CODES.VIDEO_EVENTS&&(f=m.request("videoEventsString"))&&(s.ve=f,s.clog=q);b===h.DT_CODES.UNLOAD&&(s.ndt=l);-1!==n.mode.indexOf("jsvid")&&(s.vv=m.request("videoVersion"));s.NULL1=
d.output();s.NULL2=k.stringify(10);s.em=v.embedded;s.fr=v.friendly;s.uf=u.useFlash()?1:0;s.e=c.toString();s.tt=n.mode;s.dtt=r;e.filterOutput(function(a){return!a.minDt&&(!a.type||a.type===b)},s);a.setParam("tv",s);a.setParam("br",g.getBrowserType())};m.on({sendDt:y,sendMinDt:function(a,b){y(a,b,void 0,!0)},sendDiag:a});return{send:y,sendCookie:function(){var a;d.on("cookie")&&"true"===n.sendCookie&&n.protocol&&n.cookieDomain&&n.asid&&(a=n.protocol+"://"+n.cookieDomain+"?asid="+n.asid,m.trigger("send",
a,f.noop,!0),l++)},unload:function(){s||y(h.DT_CODES.UNLOAD,-1,!0)},diagnostic:a,setViewabilityMod:function(a){u=a}}},G=function(a){var c={},d=!1,b=function(){var a={};f(c).each(function(b,d){a[b]=p.round(d)});return a},e=function(){return p.round(c.width)*p.round(c.height)};(function(){var b;a!==t.parent&&(1!==a.nodeType?c=a:f.isDef(a.getBoundingClientRect)&&(b=z.getRect(a),f(c).mixin({x:f.useIfDef(b.x)||b.scrX,y:f.useIfDef(b.y)||b.scrY,scrX:b.scrX,scrY:b.scrY,width:b.width,height:b.height})))})();
return{hasValidDims:function(){var a,b=f(c).find(function(b,d){a=!0;return isNaN(d)});return f.isDef(a)&&f.isUndef(b)},toString:function(){var a=b();return[a.scrX,a.scrY,a.width,a.height].join(".")},getRounded:b,set:function(a,b){c[a]=b},isHidden:function(){var b=1===a.nodeType?z.nodeIsHidden(a):0===a.width||0===a.height;return d?!1:b},treatAsPlaceholder:function(){d=!0},area:e,isMrcLarge:function(){return e()>=h.MRC_LARGE_AD_SIZE}}},Ha=function(){return{calcDims:function(a,c){var d=new G(a),b=z.getClippedDimensions(a,
c),e=d.getRounded();d.set("height",b.height<e.height?b.height:e.height||1);d.set("width",b.width<e.width?b.width:e.width||1);return d}}},z={nodeIsHidden:function(a){var c=this.getRect(a),d=0!==parseInt(A.getStyle(a,"width"))&&0===c.width,c=0===c.width||0===c.height;a="hidden"===A.getStyle(a,"visibility");return d||c||a},calcWinDims:function(){var a,c,d;try{c=z.windowPosition(),d=z.windowSize(),a={scrX:p.round(c.scrX),scrY:p.round(c.scrY),width:p.round(d.width),height:p.round(d.height)}}catch(b){m.trigger("error",
h.ERROR_CODES.GET_WIN_DIMENSIONS),a={}}return a},windowSize:function(){var a={},c,d;if(v.friendly)if(c=top.document,d=c.documentElement,c=c.getElementsByTagName("body")[0],f.isDef(top.innerWidth))a.width=top.innerWidth,a.height=top.innerHeight;else if(f.isDef(d.clientWidth))a.width=d.clientWidth,a.height=d.clientHeight;else if(f.isDef(c.clientWidth))a.width=c.clientWidth,a.height=c.clientHeight;else throw a.width=a.height=0,"";else f.isDef(t.outerWidth)&&(a.width=t.outerWidth,a.height=t.outerHeight);
return a},windowPosition:function(){var a=0,c=0;f.isDef(t.screenX)?(a=t.screenX,c=t.screenY):f.isDef(t.screenLeft)&&(a=t.screenLeft,c=t.screenTop);return{scrX:a,scrY:c}},getNodeArea:function(a){var c=-1;a&&(a=z.getRect(a),c=a.width*a.height);return c},getRect:function(a){var c={},d=z.windowPosition();a=a.getBoundingClientRect();f.isUndef(a.x)&&(c.x=a.left,c.y=a.top);f.isUndef(a.width)&&(c.width=a.right-a.left,c.height=a.bottom-a.top);f(c).mixin(a,!0);c.scrX=d.scrX+c.x;c.scrY=d.scrY+c.y;return c},
getIeDimObj:function(){return x.documentElement&&f.isDef(x.documentElement.clientWidth)&&x.documentElement||x.body},getPlaceholderSpan:function(){var a=x.createElement("span");f(a.style).mixin({width:"0px",height:"0px",display:"block",overflow:"hidden",visibiility:"hidden"});a.innerHTML=".";return a},createImage:function(){return new ((v.friendly?p.getTop():p.getWindow()).Image)},appendElement:function(a,c,d){var b=p.getDoc().createElement(a);c&&f(c).each(function(a,d){"style"===a&&"object"===typeof b.style&&
"function"===typeof b.style.setAttribute?"string"===typeof d&&f(d.split(";")).each(function(a,d){d=d.trim();if(d.length){var c=d.split(":");2===c.length&&(b.style[c[0].trim()]=c[1].trim())}}):b.setAttribute(a,d)});d=d||n.contextNode.parentNode;d.appendChild(b);return b},getClippedDimensions:function(a,c){var d,b,e=1E4,g=1E4;d="absolute"===A.getStyle(a,"position");if(null!==a.parentNode&&!d){do a=a.parentNode,d="OBJECT"!==a.tagName.toUpperCase(),b="inline"!==A.getStyle(a,"display"),d&&b&&(d=z.getRect(a),
e=d.width<e?d.width:e,g=d.height<g?d.height:g);while(a.parentNode!==x&&a!==c)}return{width:p.round(e),height:p.round(g)}},findChildWithLargestContent:function(a){var c=function(b){for(;b.parentNode!==a&&"inline"!==A.getStyle(b.parentNode,"display");)b=b.parentNode;return b},d=null,b=function(b){var d,c,f=null,r=-1;if(b.length)for(d=0,c=b.length;d<c;d++){var l=b[d],s=z.getNodeArea(l),h;if(h=s>r){h=void 0;if(h=l.parentNode===a)if(h=void 0,h="DIV"===l.nodeName)if(h=void 0,h=""===l.style.backgroundImage){var w=
h=void 0,B=l.childNodes;for(h=0;h<B.length;h++)1===B[h].nodeType&&(w=!0);h=!w}h=!h}h&&(f=l,r=s)}return f}(function(a){var b,d,c,f,l=[],h="iframe img a object embed div".split(" ");b=0;for(d=h.length;b<d;b++){var u=a.getElementsByTagName(h[b]);if(u.length)for(c=0,f=u.length;c<f;c++)l.push(u[c])}return l}(a));b&&(d=c(b));return d},screenSize:function(){var a={width:-1,height:-1};try{f.isDef(t.screen)&&(a={width:t.screen.width,height:t.screen.height})}catch(c){}return a},calcMonDims:function(){var a=
f(z.screenSize()).mixin({scrX:0,scrY:0});f.isDef(screen.availLeft)&&(a={scrX:t.screen.availLeft,scrY:t.screen.availTop,width:t.screen.availWidth,height:t.screen.availHeight});return a},getOurIFrameInTop:function(){for(var a,c=p.getTop(),d=p.getWindow();d!=c;)a=d,d=a.parent;return a},getOurNodeInTop:function(){var a;v.friendly&&(a=v.embedded?(a=z.getOurIFrameInTop())&&a.frameElement:n.contextNode);return a},getAncestorNodes:function(a){var c=[],d=a.ownerDocument&&a.ownerDocument.documentElement;if(d)for(;a.parentNode!==
d;)c.push(a),a=a.parentNode;return c},getTagsNamed:function(a){return p.getDoc().getElementsByTagName(a)},containsScriptTagWithSrc:function(a){return!!f(z.getTagsNamed("script")).findFirst(function(c,d){var b=d.src;return f.isFunction(a)?a(b):b===a})}},Da=function(a){return{getProps:function(){var c={};try{var d=x.createElement("span");f(d.style).mixin({position:"absolute",top:"150"});c={rpx:""===d.style.top?1:0}}catch(b){a.add(h.ERROR_CODES.ENVIRONMENT)}return c}}},va=function(){var a={},c=function(d){f.isDef(a[d])?
a[d]++:a[d]=1};m.on("error",function(a){c(a)});return{list:a,add:c,toString:function(){var d="",b;for(b in a)a.hasOwnProperty(b)&&(d+=b);return d},hasErrors:function(){for(var d in a)return!0;return!1}}},eb=function(a,c){var d=function(a){var d=[];if(a&&a instanceof Array)d=f(a).map(function(a,b){return b.val}),d.push(n.adsafeSrc,n.requrl,n.reqquery);else throw Error("Unexpected data type in ExchangeParser.getUrlList");return d};return{parse:function(b){try{var e,g=d(b),k=g&&g.length&&g.join("|"),
q=n.exchList;k&&(e=f(q).map(function(a,b){return 0<=k.indexOf(H.rot(b))?a:void 0}),e.length&&c.addItem({output:e.join(".")},"ex",{type:"UFO"}))}catch(r){a.add(h.ERROR_CODES.EXCHANGE_PARSING)}}}},ra=function(){var a={},c=function(b){var d;f.isUndef(a[b])&&(d=n.jsFeatures,a[b]=!1,-1!==d.indexOf(b)&&(d=RegExp(b+"(?=$|,)|"+b+":(?!,|$)(.?\\d*(?=,|$))").exec(d)))&&(d=d[1],a[b]=!d||d>100*p.random());return a[b]},d={fc:"forcecocoa",rt:"rattie",cb:"cachebust",np:"nextcocoa",th:"tabHiddenDtCall",es:"everySecond"},
b={gm:"use100v",fif:"useFIF"},e=function(){var c,e;c=f(d).mapToObj(function(b,d){var c={};c[b]=a[d]?1:0;return c});e=f(b).mapToObj(function(a,b){var d={};d[a]=g(b)?1:0;return d});return f(c).mixin(e)},g=function(a){a=n[a];return!0===a||"true"===a||f.isFunction(a)};f(d).each(function(a,b){c(b)});return{on:c,bootstrapOn:g,output:function(){return f(e()).toParams()}}},Ka=function(a){var c=h.BROWSERS,d=m.request("intersectionWatcher");return{calcInitialViewState:function(b,e,f){var k={IN_VIEW:65,OUT_OF_VIEW:25,
PARTIAL_VIEW:30},q={IN_VIEW:75,OUT_OF_VIEW:25,PARTIAL_VIEW:50},r=h.NA,l=!v.xDomainIframe||d.isStarted()||a.browserIs(c.GECKO)||a.browserIs(c.IE);f=f?k:q;if(l||e)r=b===h.PIV_NA?h.NA:b>=f.IN_VIEW?h.IN_VIEW:b<=f.OUT_OF_VIEW?h.OUT_OF_VIEW:b>=f.PARTIAL_VIEW?h.PARTIAL_VIEW_PLUS:h.PARTIAL_VIEW_MINUS;return r},calcPercentInView:function(a,c,g,k){var h=0,r=a;d.isStarted()?h=d.getPiv():a.hasValidDims()&&!a.isHidden()&&(f([c,g,k]).each(function(a,b){if(b.hasValidDims()){var d=r.getRounded(),c=b.getRounded(),
e=Math.max(d.scrX,c.scrX),f=Math.max(d.scrY,c.scrY),g=Math.min(d.scrX+d.width,c.scrX+c.width),d=Math.min(d.scrY+d.height,c.scrY+c.height),g=g-e,d=d-f;r=G({scrX:e,scrY:f,width:0<g?g:0,height:0<d?d:0})}}),h=p.round(r.area()/a.area()*100));return h}}},Ea=function(a){var c=!1;return{getCacheBustId:function(){var a=new Date,b=Date.parse("Jan 1 "+a.getFullYear()),a=a.getTime()-b;return f.toBase(a,62)},impressionIsIdentifiable:function(a){a&&(c=!0);return c},unq:function(){var d="";try{for(var b,c=t.Uint32Array&&
t.crypto&&t.crypto.getRandomValues;30>d.length;)c?(b=new Uint32Array(1),t.crypto.getRandomValues(b),d+=b[0].toString(16)):d+=(16*p.random()|0).toString(16);d=d.slice(0,30)}catch(f){a.add(h.ERROR_CODES.UID_GENERATION)}return d}()}},Ja=function(a){var c,d,b,e=m.request("features"),g=function(){var c,g,k,r,B=p.getMaxNumber();c=p.getMaxNumber();g=p.getWindow();p.getDoc();v.friendly?(c=q(),k=c.left,r=c.top,B=c.width,c=c.height,g=z.windowPosition(),k=g.scrX+k,r=g.scrY+r):e.on("rattie")&&a.browserIs(h.BROWSERS.IE)?
(b=b||m.request("ieXDomainViewability"),d=b.determineFramePosition(),k=d.scrX,r=d.scrY):f.isDef(g.mozInnerScreenX)&&(k=p.round(g.mozInnerScreenX),r=p.round(g.mozInnerScreenY));return{scrX:k,scrY:r,iFrameClippingWidth:B,iFrameClippingHeight:c}},k=function(){var a,b,d=c||z.getIeDimObj(),e=p.getWindow();f.isDef(e.innerWidth)?(a=e.innerWidth,b=e.innerHeight):d&&f.isDef(d.clientWidth)?(a=d.clientWidth,b=d.clientHeight,0===a&&0<d.offsetWidth&&(a=d.offsetWidth),0===b&&0<d.offsetHeight&&(b=d.offsetHeight)):
e.frameElement&&f.isDef(e.frameElement.clientWidth)&&(a=e.frameElement.clientWidth,b=e.frameElement.clientHeight);return{width:a,height:b}},q=function(a,b){a=a||p.getWindow();b=b||{top:0,left:0,width:p.getMaxNumber(),height:p.getMaxNumber()};for(var d,c=a.parent.document.getElementsByTagName("iframe"),e=!1,f=0,g=c.length;f<g;f++)if(d=c[f],d.contentWindow==a){e=!0;break}if(e){d=z.getRect(d);b.left+=d.left;b.top+=d.top;try{b.width=p.min(b.width,d.width),b.height=p.min(b.height,d.height)}catch(k){m.trigger("error",
h.ERROR_CODES.GET_AD_DIMENSIONS)}a!==p.getTop()&&q(a.parent,b)}return b},r=function(){var a={};try{a=f(g()).mixin(k())}catch(b){m.trigger("error",h.ERROR_CODES.GET_AD_DIMENSIONS)}return a};return{calcDims:function(){return new G(r())},waitForBody:function(a){var b=setInterval(function(){x.body&&(c=z.getIeDimObj(),clearInterval(b),a())},50)},getClippedDims:function(){var a=r();return new G({scrX:a.scrX,scrY:a.scrY,width:a.iFrameClippingWidth,height:a.iFrameClippingHeight})}}},Xa=function(a,c,d,b,e,
g,k,q){var r=function(a,b){var d,c,e=[],g=function(a){return-1!==a.key.indexOf("q")||-1!==a.key.indexOf("g")};d=f(a).map(function(a,b){if(g(b))return b});c=f(a).map(function(a,b){if(!g(b))return b});f(d.concat(c)).each(function(a,d){var c;c="adsafe_url="+d.val+"&adsafe_type="+d.key;var f=e.join("&").length;c.length+f<=b&&e.push(c)});return e.join("&")},l=function(){var a,e;e=q.needsFlash()?{viewState:h.NA}:q.checkScreenLoc(!0);a=function(a){return"c:"+b.getCacheBustId()+",sl:"+a.viewState+",em:"+
v.embedded+",fr:"+v.friendly}(e);e=function(a){var e,l=[];l.push("pt:"+function(){var b=q.stringifyPingTimes();a.viewState!=h.NA&&(b+=a.details);return b}());l.push(f(k.params()).toParams());l.push("id:"+n.asid);g.iterate(function(a,b){l.push(a+":"+b.output())});c.toString()&&l.push("e:"+c.toString());l.push(d.output());l.push("uf:"+(q.useFlash()?1:0));l.push("tt:"+n.mode);l.push("et:"+(p.now()-n.birthdate));l.push("uid:"+b.unq);l.push("v:1.103.0");l.push("sp:"+("true"===n.jsDoSplit?1:0));l.push("ct:"+
v.getPageTime());l.push("dtm:"+(d.on("postDts")&&A.getXHR2()?"p":"i"));l.push("mn:"+n.mn);l.push("gtpl:"+("true"===n.getTpl?1:0));d.on("resolution")&&(l.push("wr:"+f(z.windowSize()).toArray().join(".")),l.push("sr:"+f(z.screenSize()).toArray().join(".")));(e=function(){var a,b,d;d=H.hashCode(n.asid)+"";b=k.params().br.toUpperCase().charCodeAt(0);-1===d.indexOf(b)&&(a=d);return a}())&&l.push("mf:"+e);return l}(e);return{primary:a,secondary:e}},s=function(a,d){var c="adsafe_jsinfo=",e=0,g="true"===
n.jsDoSplit?1:0,k=function(a){if(a)return","+a};c.length+a.primary.length+5<=d&&(c+=k(a.primary),f(a.secondary).each(function(a,f){-1!==f.indexOf("id:")&&c.length+f.length+5<=d?(c+=k(f),b.impressionIsIdentifiable(!0)):c.length+f.length+5<=d?c+=k(f):e+=1}),k("sp:"+g));return c+=",ov:"+e};return{send:function(a){try{var b,f,g,k,q;b=e.baseUrl;g=d.on("bigmon")&&"jload"===n.mode?4E3:2E3;try{f=g-b.length-0,0<f&&(b+=r(a,f))}catch(p){c.add(h.ERROR_CODES.IMPRESSION_URLS)}b+="&"===b.slice(-1)?"":"&";try{q=
g-b.length,k=l(),b+=s(k,q)}catch(t){c.add(h.ERROR_CODES.JSINFO),b+="adsafe_jsinfo=e:"+c.toString()}e.macroUrl&&(b+="&"===b.slice(-1)?"":"&",b+=e.macroUrl);e.sendImpression(b);m.trigger("impressionsent")}catch(v){__IntegralASDiagnosticCall("impsend",v,n)}}}},Ua=function(a,c){return{init:function(d){a.jsonp(d,function(a){c.send(h.DT_CODES.THIRD_PARTY,void 0,!1,!0,{field:"tpiLookup",value:a})},!1,"callback")}}},Qa=function(a){var c=function(a,d){return{time:a,task:d}},d=function(a,d){d=d||f.noop;return function(g){return f(g).map(function(f,
g){var h=g/1E3;return new c(g,function(){var c;c="";var f=v.isVideo()?2:1;h!==f&&(c+=h);c=n["_onInViewMRC"+c];m.trigger("sendDt",a,h);d(c)})})}};return{getJob:function(a,d){return new c(a,d)},getPingJobs:d(h.DT_CODES.PING,function(b){"true"===n.useViewabilityNotification&&!a.skipAsFraudulent()&&b&&m.trigger("notify",b)}),getFullyInViewPingJobs:d(h.DT_CODES.FULLY_INVIEW),getPosInViewPingJobs:d(h.DT_CODES.POS_INVIEW)}},Ba=function(){var a=function(a,b){-1!==a.indexOf(b+"&")&&(b+="&");return a.replace(b,
"")},c=function(a,b,c){var f=a.indexOf("?");b=b+"="+c;if(-1===f)return a+"?"+b;f++;return a.slice(0,f)+b+"&"+a.slice(f)};return{wrap:function(d,b,e,f){var k="__IntegralAS_"+n.asid.replace(/\-/g,"")+"_"+p.round(1E4*Math.random()),h,r,l;f=f||"ias_callback";RegExp(f).test(d)&&(h=RegExp("("+f+"=)(.[^&]*)").exec(d)[0],r=h.split("=")[1],l=H.stringToFn(r),d=a(d,h));t[k]=function(a){b(a);e&&l&&l(a);t[k]=void 0};return d=c(d,f,k)}}},Va=function(a,c){var d={jss:{isFW:!0,nodeType:"script"},rjss:{isFW:!0,nodeType:"script"},
jsi:{isFW:!0,nodeType:"iframe"},rjsi:{isFW:!0,nodeType:"iframe"},jload:{impressionMethod:function(b){a.enabled?m.trigger("jsonp",b,a.callback,!0):m.trigger("send",b,function(){m.trigger("sendDiag")},!c.on("postMon"))}},bapi:{impressionMethod:function(b){m.trigger("jsonp",b,a.enabled?a.callback:f.noop,a.enabled?!0:!1)}},jsapi:{isFW:!0,impressionMethod:function(b){m.trigger("jsonp",b,a.enabled?a.callback:f.noop,a.enabled?!0:!1)}},jsvid:{impressionMethod:function(b){m.on("adImpression",function(){a.enabled?
m.trigger("jsonp",b,a.callback,!0):m.trigger("send",b,f.noop,!c.on("postMon"))})}},fwjsvid:{isFW:!0,impressionMethod:function(a){var d="false"===n.fwMonitoring,c=function(a){a=a.split("/");a[3]="db2";a[4]="video";return a.join("/")};d&&m.trigger("jsonp",c(a),function(a){m.trigger("videoBlockResult",a)});m.on("adImpression",function(c){var g;if(g=d)g=c&&f.isBool(c.integral_didBlock)&&0<=c.integral_timeToDecision;g&&(a=a.replace(/(adsafe_jsinfo=)([^&]*)/,"$1$2,abc:"+(c.integral_didBlock?1:0)+",abct:"+
c.integral_timeToDecision));m.trigger("send",a,f.noop,!0)})}},jspix:{nodeType:"img"}};return new function(){var a=function(a){var b=-1===a.indexOf("?")?"?":"&";return a+b},c=d[n.mode],f=!!c.isFW,k=function(a){var b;b=m.request("mobileApp").isMobileAppEnvironment()&&n.mobFwUrl?n.mobFwUrl:a?n.adsafeSrc:n.requrl;a||(b+="?"+n.reqquery);return b}(f),h=k.indexOf("BEGIN__ADSAFE"),r=-1!==h,l=r?k.slice(h):"",a=r?k.slice(0,h):a(k);return{isFW:f,baseUrl:a,macroUrl:l,sendImpression:function(a){c.nodeType?m.trigger("addNode",
c.nodeType,a):c.impressionMethod(a)}}}},db=function(a,c){var d,b=n.mtCell,e=n.mtSample,g=0,k=0,q=[],r=null,l=null,s,m=function(a){try{var d=p.now()-r;g+=d;A.removeEvent("mousemove",B);q.push("{ht:"+g+",mm:{"+f(s).toParams()+"}}");c.addItem({output:"{cs:"+b+",sr:"+e+",ec:"+q.length+",me:["+q.slice(-10).join(",")+"]}"},"mt",{type:h.DT_CODES.UNLOAD})}catch(k){}},w=function(a){try{g=0,s={},r=p.now(),A.addEvent(d,"mousemove",B)}catch(b){}},B=function(c){var g,h,r,q,m,n,B;try{null===l&&(l=d&&f.isDef(c.clientX)&&
f.isDef(c.clientY));if(l&&0===k%e&&(m=a.calcDims(),-1!==m)){B=p.ceil(m.width/b);var u=c.clientX,w=c.clientY;r=v.embedded?u:u-m.x;q=v.embedded?w:w-m.y;g=p.floor(r/b);h=p.floor(q/b);n=g+h*B;s[n]?s[n]++:s[n]=1}k++}catch(t){}};return{init:function(){var b=setInterval(function(){try{a.isAdDetected()&&(d=a.getOriginatingElement(),A.addEvent(d,"mouseenter",w),A.addEvent(d,"mouseleave",m),clearInterval(b))}catch(c){}},250)}}},p={execAtEndOfThread:function(a){setTimeout(a,0)},now:function(){return(new Date).getTime()},
random:function(){return Math.random()},round:function(a){return Math.round(a)},ceil:function(a){return Math.ceil(a)},floor:function(a){return Math.floor(a)},min:function(){return Math.min.apply(null,arguments)},distance:function(a,c){return Math.abs(a-c)},getWindow:function(){return t},getMaxNumber:function(){return Number.MAX_VALUE},getTop:function(){return top},getNewActiveXObject:function(a){return new ActiveXObject(a)},getDoc:function(){return x},getIntersectionObserver:function(a,c){return new IntersectionObserver(a,
c)}},ya=function(){var a,c=!1,d=m.request("features"),b=new X,e=function(){var b;d.on("blur")?(b=p.getWindow(),b=v.friendly&&b.top.document&&(f.isFunction(b.top.document.hasFocus)||f(b.top.document.hasFocus).isObj())&&!b.top.document.hasFocus()||(f.isDef(a.prop)?p.getDoc()[a.prop]:null)):b=f.isDef(a.prop)?p.getDoc()[a.prop]:null;return b},g=function(){var d=p.getWindow(),c=function(){b.run(e())};A.addEvent(d,"focus",c,!0);A.addEvent(d,"blur",c,!0);a.event&&A.addEvent(p.getDoc(),a.event,c,!0)};a=function(){var a,
b="hidden",d="visibilitychange",c=p.getDoc();f.isUndef(c.hidden)?f(["moz","ms","webkit"]).each(function(e,g){var h=g+"Hidden";f.isDef(c[h])&&(b=h,d=g+d,a=!0)}):a=!0;return a?{prop:b,event:d}:{}}();return{isHidden:e,onHiddenChange:function(a){b.push(a);c||(c=!0,g())}}},za=function(){var a=function(a){for(var b in a)if(a.hasOwnProperty(b)){var c=a[b];(""===c||"null"===c||"undefined"===c||null===c||f.isUndef(c))&&delete a[b]}return a},c=function(a){var b={},c,g;for(g in a)a.hasOwnProperty(g)&&(c=a[g],
f.isUndef(b[c])?b[c]=g:b[c]+=g);a={};for(g in b)b.hasOwnProperty(g)&&(c=b[g],a[c]=g);return a};return{detectTopURL:function(){var d=function(){var a={g:"",q:""};try{a.q=t.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.location.href}catch(b){var c=b.message,c=c.substring(c.lastIndexOf("<")+1,c.lastIndexOf(">")),d;if(d=f.isDef(c))if(d=!1,f.isDef(t.navigator)&&f.isDef(t.navigator.userAgent)){var e=t.navigator.userAgent.match(/Firefox\/([\.0-9]+)/);null!==e&&2==e.length&&(e=e[1].split("."),
3==parseInt(e[0],10)&&6>=parseInt(e[1],10)&&(3==e.length?13>=parseInt(e[2],10)&&(d=!0):d=!0))}d&&(a.g=c)}return a},b={};try{b.a=encodeURIComponent(top.location.href)}catch(e){}try{b.b=encodeURIComponent(parent.location.href)}catch(g){}if(v.embedded){try{b.c=encodeURIComponent(parent.document.referrer)}catch(k){}try{b.e=encodeURIComponent(t.document.referrer)}catch(h){}}try{"jsi"!==n.mode&&(b.d=encodeURIComponent(t.location.href))}catch(r){}try{b.f=encodeURIComponent(n.jsref)}catch(l){}try{var s=d();
b.g=encodeURIComponent(s.g);b.q=encodeURIComponent(s.q)}catch(m){}var b=a(b),b=c(b),d=[],p;for(p in b)b.hasOwnProperty(p)&&d.push({key:p,val:b[p]});d.sort(function(a,b){return a.val.length>b.val.length?1:a.val.length<b.val.length?-1:0});return d}}},fb=function(a){return{hash:function(){for(var c=0,d=a.length,b=[],e;c<d;c++)e=a[c].filename.replace(/\.plugin$/,""),e=H.hashCode(e),e=f.toBase(e,62).slice(-4),b.push(e);return b},decode:function(c){var d,b;d=p.floor(p.random()*c.length);b=encodeURIComponent(a[d].filename.replace(/\.plugin$/,
""));return[c[d],b]}}},ua=function(a){var c=!1;return{measure:function(d){(c=0===d.rsa)&&n._onSuspicious&&a.trigger("notify",n._onSuspicious)},skipAsFraudulent:function(){return c}}},Aa=function(){var a=[],c={},d={sl:"n",gsl:"gn",fsl:"fn"},b=0,e,g,k={i:0,o:0,n:0,pp:0,pm:0,gpp:0,gpm:0,gi:0,go:0,gn:0,fi:0,fo:0,fn:0},q=function(a){var b={},c=a.winDimensions,d=a.adDimensions;f.isDef(c)&&c.hasValidDims()&&(b.wc=c);f.isDef(d)&&d.hasValidDims()&&(b.ac=d,b.am=a.method,b.cc=a.containerDimensions);f({piv:"percentInView",
obst:"obstructed",th:"tabHidden",reas:"reason",cmps:"adCompCount"}).each(function(c,d){var e=a[d];f.isDef(e)&&(b[c]=e)});c=f(b).toParams();return""===c?"":","+c},r=function(a,b){var d=new ub(b);return c[a]=d},l=function(a,b){return(b||"")+{inView:"i",outOfView:"o",na:"n",partialViewMinus:"pm",partialViewPlus:"pp"}[a]},s=function(){f(d).each(function(c,d){k[d]+=a.length?g-b:g});b=g},n=function(b){a.length&&s();f(b).each(function(a,b){var c=d[a];c!==b&&"n"===c&&(k[b]+=k.n);d[a]=b});a.length||s()},p=
function(a){var b,d=a.adDimensions.getRounded();b=q(a);var e={sl:l(a.viewState),fsl:l(a.fState||h.NA,"f"),gsl:l(a.gState||h.NA,"g")};g=v.getTagTime();n(e);e.t=g;b=f({toString:function(){f(c).each(function(a,b){b.fastForward()});return"{"+f(e).toParams()+this.details+this.breakdowns+"}"},details:b,breakdowns:{piv:[],as:[],toString:function(){var a,b=function(a,b){return b.duration+"~"+b.state};a=""+("piv:["+f(this.piv).stringify(b)+"]");a+=",as:["+f(this.as).stringify(b)+"]";return",bkn:{"+a+"}"}},
isInView:function(){return-1!==(h.IN_VIEW+"|"+h.PARTIAL_VIEW_PLUS).indexOf(a.viewState)},isFullyInView:function(){var b=a.useCocoa?a.fullPercentInView:a.percentInView;return this.isInView()&&100===b}}).mixin(e);f(b).mixin(a);b.width=d.width;b.height=d.height;return b};(function(){r("piv",function(a){var b,c=a.percentInView,d=[1,25,30,50,75];100===c||0===c?b=c:(f(d).each(function(a,e){f.isUndef(b)&&c<e&&(b=d[a-1])}),f.isUndef(b)&&(b=d[d.length-1]));return b});r("as",function(a){a=a.adDimensions.getRounded();
return a.width+"."+a.height})})();return{fastForward:function(){g=v.getTagTime();s()},registerLocation:function(b){var g,k=!1;d.sl==l(b.viewState)&&a.length?(g=new p(b),a[a.length-1].details=g.details):(g=new p(b),a.push(g),e=b.viewState,k=!0);m.trigger("newScreenEvent",g);f(c).each(function(b,c){-1!=="piv|as".indexOf(b)?(k&&c.clear(),c.addState(g),a[a.length-1].breakdowns[b]=c.get()):c.addState(g)});return g},stringify:function(b){var c="";a.length&&(c=f({slTimes:"{"+f(k).toParams()+"}",slEvents:"["+
a.slice(-b).join(",")+"]",slEventCount:a.length}).toParams());return c},createViewabilityTracker:r,getCurrentLoc:function(){return l(e)}}},Ya=function(a){var c=n.asid,d=[0,1,4],b,e=function(){var a=setInterval(function(){t.postMessage({asid:c,ksca:"acsk",sender:"main"},"*")},50);t.addEventListener("message",function(b){b=b.data;"acsk"===b.ksca&&b.asid===c&&"main"!==b.sender&&("ack"===b.type&&clearInterval(a),"complete"===b.type&&(b.timeReturned=p.now(),g(b)),d.length&&(b=d.shift(),t.postMessage(k(b),
"*")))})},g=function(b){var c=-5-0.1*b.targets,d=h.DT_CODES.SCA;b="{"+f(b).stringify(function(a,b){var c;0===a.indexOf("time")?c=a+":"+b:"resultList"===a&&(c="rl:"+f(b).map(function(a,b){return"{"+f(b).toParams()+"}"}).join("."));return c})+"}";a.trigger("addOutputItem",{output:b},"sc",{type:d});a.trigger("sendDt",d,c)},k=function(){var a=0,d=c.replace("-",""),e=d.substr(-6);return function(f){for(var g=b,k=p.now(),h=f,m=[];h--;)m.push(d.substr(++a,3));return{scaUrl:g,targets:f,timeBegun:k,src:e,
targetList:m,asid:c,ksca:"acsk",sender:"main",cap:1E6}}}();return{load:function(){if(!f.isUndef(t.Worker)&&!f.isUndef(t.Blob)){var c=new O;c.sub("static");c.master(c.master().split(":")[0]);c.path("sca.js");b=c.toString();a.trigger("exec",b);e()}}}},H={rot:function(a){return a.replace(/[a-zA-Z]/g,function(a){return String.fromCharCode(("Z">=a?90:122)>=(a=a.charCodeAt(0)+13)?a:a-26)})},hashCode:function(a){var c=0,d,b,e;if(0===a.length)return c;d=0;for(e=a.length;d<e;d++)b=a.charCodeAt(d),c=(c<<5)-
c+b,c|=0;return c},stringToFn:function(a){var c,d=t,b=a.split(".");for(a=0;a<b.length;a++)if(c=d,d=d[b[a]],f.isUndef(d)||a===b.length-1&&!f.isFunction(d))return!1;return function(){d.apply(c,arguments)}},stringToProp:function(a){var c=p.getWindow(),d=a.split(".");for(a=0;a<d.length&&(c=c[d[a]],!f.isUndef(c));a++);return c}},sa=function(a){var c,d,b,e=new V,g=new Y,k=new wb(e),h=new xb,r=new yb(e,a),l=f.isDef(t.JSON)&&f.isDef(t.postMessage),s=function(){f.isUndef(b)&&(b=new zb(e));return b},m=function(){e.provide({frameCollection:function(){return k},
adProxy:function(){return h},adTalkMessage:function(a){return new Ab(a,e)},idMapModule:s})};return{isApplicable:function(){return l},start:function(){m();g.traverse(k.addFrame);r.startListening();r.sendToKnownFrames()},sendAdTalkCall:r.sendAdTalkCall,getFrameMap:function(){f.isUndef(c)&&(c=new na(e));return c},getFrameMapIncludingPeerCase:function(){f.isUndef(d)&&(d=new na(e,!0));return d},getIdMap:s}},Ab=function(a,c){var d=c.request("adProxy").myIdCard,b={messageContent:a||{},srcAsid:n.asid,srcTagId:d.tagId,
srcIsEmbedded:v.embedded,srcBirthdate:n.birthdate,iasCommonId:n.asid.split("-")[2],updateMessage:function(c){b.messageContent=c(a)}};return b},Bb=function(a,c,d,b){var e,g=a==t;e={position:c.slice(0),id:c.join("-"),isMe:g,isLeaf:!a.frames.length,adProxies:g?d:[],selfDescription:void 0,unifiedId:n.birthdate,srcIsEmbedded:b?b.srcIsEmbedded:void 0,inbox:b?[b]:[],getDomObj:function(){return a},getStringifiedPosition:function(){return f(e.position).map(function(a,b){return f.toBase(Number(b)+1,36)}).join("")},
isValidForMapping:function(){return e.isLeaf||e.isMe||f.isDef(e.selfDescription)}};var k=function(a){var b=e.adProxies;a=a.adProxies;var c=[];b.length&&a.length?f(a).each(function(a,d){h(b,d)&&c.push(d)}):c=a;e.adProxies=b.concat(c)},h=function(a,b){return!f(a).find(function(a,c){return c.adSafeId&&c.adSafeId===b.adSafeId})},r=function(a){f(e.inbox).find(function(b,c){return c.srcAsid&&c.srcAsid===a.srcAsid})||e.inbox.push(a)};e.addInformationFromSrc=function(a,b){k(b);r(a);e.srcIsEmbedded=a.srcIsEmbedded;
e.selfDescription=b};return e},wb=function(a){var c=[],d={},b={noMe:!0};return{addFrame:function(e,f,k){var h=a.request("adProxy").getAll();e=new Bb(e,f,h,k);c.push(e);d[e.id]=e;e.isMe&&(b=e);return e},getFrame:function(a){return d[a]},list:c,dictionary:d,getMe:function(){return b}}},na=function(a,c){var d=function(a,d){var f=d.adProxies,h="";if(d.isValidForMapping()){if(c)h+=b(f,d.getStringifiedPosition());else{var r;r=""+d.getStringifiedPosition();r+=d.isMe?"*":"";r+=f.length?"."+f[0].tagId:"";
h+=r}return h}},b=function(a,b){var c="";return c=a.length?c+f(a).stringify(function(a,c){return b+(n.asid===c.adSafeId?"*":"")+"."+c.tagId},"|"):c+b};return{output:function(){var b=a.request("frameCollection"),c=f(b.list).stringify(d,"|");return f.toBase(b.getMe().unifiedId,62)+"+"+c}}},zb=function(a){var c=a.request("frameCollection"),d=c.getMe().getStringifiedPosition(),b=function(a,b){var c,f=[];c=b.getStringifiedPosition();var h=b.inbox;b.isMe&&f.push(d+"*");b.isValidForMapping()&&g(b)&&h.length&&
(c=e(h,c))&&f.push(c);return(f=f.join("|"))?f:void 0},e=function(a,b){var c;return c=""+f(a).stringify(function(a,c){var d;c.srcAsid&&n.asid!==c.srcAsid&&c.transferDuration?(d=c.srcTagId,d=b+"."+c.srcAsid+"."+c.transferDuration+"_"+d):d=void 0;return d},"|")},g=function(a){var b;if(b=a.srcIsEmbedded&&v.embedded)a=a.getStringifiedPosition(),b=0===d.indexOf(a)||0===a.indexOf(d);return b};return{output:function(){var a=f(c.list).stringify(b,"|");return a=120<a.length?a.substr(0,120)+".of"+a.length:a},
isCandidateForMyIdMap:g}},yb=function(a,c){var d=!1,b=function(a){var b=n.asid.split("-")[2];return a.hasOwnProperty("messageContent")&&b===a.iasCommonId},e=function(){var b=a.request("frameCollection").getMe();return a.request("adTalkMessage",{self:b,unifiedId:b.unifiedId})},g=function(a,b){if(!a)return!0;var c;c=f(a.inbox).find(function(a,c){return c.srcAsid&&c.srcAsid===b.srcAsid});return b.srcAsid!==n.asid&&!c},k=function(){var b=h.DT_CODES.ADTALK;a.request("frameCollection");d||(d=!0);m.trigger("sendDt",
b)},q=function(b,c,e){var q,n,t,y,x;try{q=a.request("frameCollection");n=c.messageContent;t=n.self;var z=q.getMe();z.unifiedId>t.unifiedId&&(z.unifiedId=t.unifiedId);var A;A=p.now()-c.sentTime;c.transferDuration=A;y=q.getFrame(t.id);x=g(y,c);f.isUndef(y)||f.isUndef(y.selfDescription)||(n.srcIsEmbedded||v.embedded)&&x?(y=y||q.addFrame(b.source,t.id.split("-"),c),y.addInformationFromSrc(c,t),e()):y.addInformationFromSrc(c,t);b=y;var C=a.request("idMapModule");d&&x&&C.isCandidateForMyIdMap(b)&&k()}catch(G){m.trigger("error",
h.ERROR_CODES.ADTALK_DUBIOUS)}};return{sendAdTalkCall:k,sendToKnownFrames:function(){(new Z).send(e)},startListening:function(){(new W).listen(b,q,e)},validateMessage:b,processMessage:q,createMessage:e}},Cb=function(a){a=a||n;var c;a.reqquery?c=a.reqquery.split(/(?:anId=|anid=|ANID=)([^&]*)/)[1]:(c=a.adsafeSrc.split("/"),c=c[5]+"-"+c[6]);return{tagId:c,adSafeId:a.asid}},xb=function(){var a,c=[],d=function(a){a=new Cb(a);c.push(a);return a};a=d();return{createNew:d,getAll:function(){return c},myIdCard:a}},
Ia=function(a){var c,d,b=!1,e=p.getDoc().documentElement,f=function(a){var e=!0;b&&(b=!1,a.stopPropagation(),a.preventDefault(),c=a.screenX-a.clientX,d=a.screenY-a.clientY,e=!1);return e};a.browserIs(h.BROWSERS.IE)&&A.addEvent(e,"click",f,!0);return{determineFramePosition:function(){a.browserIs(h.BROWSERS.IE)&&(b=!0,e.click());return{scrX:c,scrY:d}}}},Ga=function(a){var c=h.NA,d=!1;return{getPiv:function(){return c},isApplicable:function(a,c,d){return a.browserIs(h.BROWSERS.CHROME)&&a.hasIntersectionObserver()&&
d.xDomainIframe&&c.on("chromeNativeIO")},start:function(){var b=p.getIntersectionObserver(function(a){a=a.pop();c=a.intersectionRect.width*a.intersectionRect.height/(a.boundingClientRect.width*a.boundingClientRect.height)*100},{threshold:[0,0.01,0.25,0.3,0.5,0.75,0.99,1]});p.execAtEndOfThread(function(){c=0});b.observe(a);p.execAtEndOfThread(function(){m.trigger("delayedViewabilityReady")});d=!0},isStarted:function(){return d}}},$a=function(a,c,d){var b=!1,e=function(){c.impressionIsIdentifiable()&&
!b&&(b=!0,m.trigger("notify",n._onMeasurable))};return{start:function(){var b=m.request("mobileApp");if(b.isMobileAppEnvironment()?b.isMeasurable():!d.useFlash())e();else m.on("measurable",function(){a.browserIs(h.BROWSERS.WEBKIT)||e()})},isApplicable:function(a){return a.bootstrapOn("useViewabilityNotification")&&f.isDef(n._onMeasurable)}}},Wa=function(a,c,d,b,e,g,k,m,r,l,s,u,w,B){var y,z,F,E,C,I=0,J=0,K=!1,H=-1!==n.mode.indexOf("jsvid"),P=g.request("mobileApp"),O=H?200:100;d=n.mobOrTab;var U=!d&&
b.on("recordalternate")&&!b.bootstrapOn("killFlash"),L=a.hasFlashEnabled(),V=b.on("forcecocoa")&&L,M=b.on("nextcocoa");a.getDocumentMode();var Q=g.request("intersectionWatcher"),Q=a.browserIs(h.BROWSERS.GECKO)||a.browserIs(h.BROWSERS.IE)&&b.on("rattie")||Q.isApplicable(a,b,v),da=v.friendlyIframe&&V||v.xDomainIframe&&Q&&V||v.xDomainIframe&&!Q,N=!d&&da&&b.on("cocoapuffs")&&L&&!b.bootstrapOn("killFlash"),S=!1,T=new vb(10),ea=M?la:ma,R=[H&&b.on("videotwoseconds")?2E3:1E3,5E3,15E3];b.on("everySecond")&&
(R=[1E3,2E3,3E3,4E3,5E3,6E3,7E3,8E3,9E3,1E4,11E3,12E3,13E3,14E3,15E3]);var X=f(R).map(function(a,b){return b/1E3}).join("-"),aa=new ha(1E3),W=new ga(l.getPingJobs(R));if(b.on("hundredpct")&&n.use100v)var ca=new ha(1E3),Y=new ga(l.getFullyInViewPingJobs(R));if(b.on("tabHiddenDtCall"))var ba=new ha(1E3),Z=new ga(l.getPosInViewPingJobs([R[0]]));var ia=function(){$();b.on("viewabilityready")&&!K&&(c.send(h.DT_CODES.VIEWABILITY_READY),g.trigger("measurable"),K=!0)};g.on("delayedViewabilityReady",ia);var $=
function(d){try{T.start();var k,l,m,q,t,v;m=u.collect();U&&(m.gState=m.viewState);if(P.isMobileAppEnvironment())m.viewState=P.getViewabilityResult(),m.method=P.getDetectionMethod(),m.percentInView=P.getPercentageInView();else if(N){y=y||new fa(ea,m.adDimensions,ia,b,s,a)||{};q=y.checkViewable();b.on("hundredpct")&&n.use100v&&(E=E||new pb(ob,m.adDimensions,ia,a,b,e,r,s)||{},t=E.checkViewable(),m.fullPercentInView=t.pct,m.useCocoa=N);if(1!==m.tabHidden||q.str===h.NA)m.viewState=q.str;m.percentInView=
q.pct;b.on("unreliabilityDetection")&&L&&(F=F||new fa(ea,G({height:0,width:-2E4}),f.noop,b,s,a)||{},v=F.checkViewable(),v.str!==h.OUT_OF_VIEW&&(J+=1),I+=1,r.addItem({output:J+"/"+I},"fu"))}else da&&(m.viewState=h.NA,m.percentInView=h.PIV_NA);U&&(z||d||!L||(z=N?y:new fa(ea,m.adDimensions,f.noop,b,s,a,e)),m.fState=d||!L?h.NA:z.checkViewable().str);if(H&&(l=B.getViewStateOverride())){if(l===h.OUT_OF_VIEW){var x=m.reason?m.reason.split("."):[];x[x.length]=h.OUT_OF_VIEW_REASONS.VIDEO;m.reason=x.join(".")}m.viewState=
l}k=w.registerLocation(m);b.on("hundredpct")&&n.use100v&&(k.isFullyInView()?(ca.mark(),Y.doEligibleJobs(ca.getTotalTime()),!b.on("zeroPing")||S||d||(c.send(h.DT_CODES.FULLY_INVIEW,0),S=!0)):ca.stop());k.isInView()?(aa.mark(),W.doEligibleJobs(aa.getTotalTime())):aa.stop();var A=W.getNextJob();A&&A.time===R[0]&&b.on("tabHiddenDtCall")&&(m.posViewState===h.IN_VIEW||m.posViewState===h.PARTIAL_VIEW_PLUS?(ba.mark(),Z.doEligibleJobs(ba.getTotalTime())):ba.stop());T.stop();var C=p.round(T.getTime()/T.getCount());
r.addItem({output:C},"lt",{type:h.DT_CODES.UNLOAD});return k}catch(K){g.trigger("error",h.ERROR_CODES.CHECK_SCREEN_LOC)}},ja,ka=function(a){var b;C=!0;var d=!1,e=function(){d||(d=!0,c.send(h.DT_CODES.VIDEO_EVENTS,void 0,void 0,void 0,void 0,function(){t.postMessage(JSON.stringify({id:n.videoId,msg:"unloadComplete",messageType:"misc"}),"*")}))};a=function(){e();if(!ja){var a=[y,E,z,F];b&&clearInterval(b);f(a).each(function(a,b){b&&"function"===typeof b.removePixels&&b.removePixels()});ja=!0}};k.impressionIsIdentifiable()&&
($(),b=setInterval($,O),ja=!1,g.on("adStopped",a),g.on("adVideoComplete",a),g.on("skipAd",a),A.addEvent(t,"beforeunload",c.unload,!1),H&&A.addEvent(t,"beforeunload",e,!1))};return{checkScreenLoc:$,init:function(){"true"===n.allowViewability&&f.isFunction(x.addEventListener)?(C=!1,"complete"==x.readyState||"loaded"==x.readyState||"interactive"==x.readyState?p.execAtEndOfThread(ka):x.addEventListener("DOMContentLoaded",ka,!1)):m.waitForBody(ka)},needsFlash:function(){return da},readyFired:function(){return C},
useFlash:function(){return N},stringifyPingTimes:function(){return X}}},qa=function(a){function c(){var a=e.isSafeToInjectMraid();d=Db().resolve(a)}var d,b=new Eb,e=new Fb;try{a.bootstrapOn("mobOrTab")&&(b.detect(),b.hasDetectedMobileApp()&&(e.detect(),c()))}catch(g){m.trigger("error",h.ERROR_CODES.MOBILE_APP)}return{isMobileAppEnvironment:function(){return b.hasDetectedMobileApp()},isMeasurable:function(){return f.isDef(d)&&d.isMeasurable()},getPercentageInView:function(){var a=h.NA;f.isDef(d)&&
d.isMeasurable()&&(a=d.getPercentageInView());return a},getViewabilityResult:function(){var a=h.NA;f.isDef(d)&&d.isMeasurable()&&(a=d.getViewabilityResult());return a},getDetectionMethod:function(){var a=h.NA;f.isDef(d)&&d.isViewabilitySupported()&&(a=d.getDetectionMethod());return a}}},Gb=function(){var a=!1,c=!1,d=p.getWindow(),b=function(){var a=d.avid;return f.isDef(a)&&f.isDef(a.getPercentageInView)},e=function(){return b()&&c},g=function(){c=!0;a&&e()&&m.trigger("delayedViewabilityReady")};
(function(){var c=d.avid;b()&&("loading"===c.getState()?(a=!0,c.addEventListener("ready",function(){g()})):g())})();return{isViewabilitySupported:b,isMeasurable:e,getViewabilityResult:function(){return 50<=d.avid.getPercentageInView()?h.IN_VIEW:h.OUT_OF_VIEW},getPercentageInView:function(){return d.avid.getPercentageInView()},getDetectionMethod:function(){return h.DETECTION_METHODS.AVID}}},Hb=function(){var a=!1,c=p.getWindow().avid,d=!1,b,e=function(){!d&&g()&&(m.trigger("delayedViewabilityReady"),
d=!0)},g=function(){return k()&&a},k=function(){return f.isDef(b)};c.addEventListener("ready",function(){a=!0;e()});c.addEventListener("viewability",function(a){b=a.eventData.percentageInView;e()});return{isViewabilitySupported:k,isMeasurable:g,getViewabilityResult:function(){return 50<=b?h.IN_VIEW:h.OUT_OF_VIEW},getPercentageInView:function(){return b},getDetectionMethod:function(){return h.DETECTION_METHODS.AVID}}},Ib={url:{STRINGIFIED_METHOD:"u",detect:function(a){return!!f(a).findFirst(function(a,
d){return-1!==p.getWindow().location.href.indexOf(d)})}},userAgent:{STRINGIFIED_METHOD:"a",detect:function(a){return!!f(a).findFirst(function(a,d){var b;b=!1;var e=p.getWindow();f.isDef(e.navigator)&&f.isDef(e.navigator.userAgent)&&(b=(b=e.navigator.userAgent)&&-1!==b.indexOf(d));return b})}},javascript:{STRINGIFIED_METHOD:"j",detect:function(a){return!!f(a).findFirst(function(a,d){return f.isDef(H.stringToProp(d))})}},scriptSrc:{STRINGIFIED_METHOD:"s",detect:function(a){return!!f(a).findFirst(function(a,
d){return z.containsScriptTagWithSrc(function(a){return f.isDef(a)&&-1!==a.indexOf(d)})})}}},oa=function(){var a=function(a,d){var b,e=Ib[a];e.detect(d)&&(b=e.STRINGIFIED_METHOD);return b};return{process:function(c){return f(c).map(a).join("")}}},Jb={url:["file:","content:","applewebdata:","afma-sdk","adsx.greystripe.com/openx/www/delivery/ia.php"],userAgent:["QuantcastSDK","afma-sdk"],scriptSrc:["file:"],javascript:["ADMARVEL","mopubFinishLoad","InmobiObj","PandoraApp","mraid.sasSendMessage"]},Eb=
function(){var a,c=function(){return void 0!==a&&""!==a};return{detect:function(){a=oa().process(Jb);c()&&m.trigger("addOutputItem",{output:"1"},"mapp",{type:"impression"})},hasDetectedMobileApp:c}},Db=function(){return{resolve:function(a){var c,d=p.getWindow(),b=d.avid;f.isDef(b)?(a=f.isDef(b.getAvidAdSessionContext)?b.getAvidAdSessionContext().avidApiLevel:"1",c="2"===a?new Hb:new Gb):f.isDef(d.mraid)||a?c=new Kb:m.trigger("addOutputItem",{output:"na"},"mi",{type:"impression"});return c}}},Kb=function(){var a=
!1,c=!1,d=!1,b=p.getWindow(),e=function(){var a=b.mraid;return f.isDef(a)&&f.isDef(a.isViewable)},g=function(){return e()&&d},k=function(){d=!0;c&&g()&&m.trigger("delayedViewabilityReady")},q=function(){var d=b.mraid;e()&&(a=!0,"loading"===d.getState()?(c=!0,d.addEventListener("ready",function(){k()})):k())},r=function(){a||(c=!0,q())};(function(){var a=!0;if(p.getWindow().mraid||z.containsScriptTagWithSrc("mraid.js"))a=!1;m.trigger("addOutputItem",{output:f.stringifyTriState(a)},"mi",{type:"impression"});
return a})()?m.trigger("exec","mraid.js",r):q();return{isViewabilitySupported:e,isMeasurable:g,getViewabilityResult:function(){return b.mraid.isViewable()?h.IN_VIEW:h.OUT_OF_VIEW},getPercentageInView:function(){return b.mraid.isViewable()?100:0},getDetectionMethod:function(){return h.DETECTION_METHODS.MRAID}}},Fb=function(){var a=[],c=[],d=function(b,c){var d,f=oa().process(c.detectionRules);f&&(a.push(c.STRINGIFIED_SDK+"*"+f),d=c);return d};return{detect:function(){c=f(Lb).map(d);0<c.length&&m.trigger("addOutputItem",
{output:function(){return a.join(".")}},"sdk",{type:"impression"})},isSafeToInjectMraid:function(){return 1==c.length&&f.isDef(c[0].safeToInjectMraid)&&c[0].safeToInjectMraid}}},Lb=[{STRINGIFIED_SDK:"adma",safeToInjectMraid:!0,detectionRules:{javascript:["ADMARVEL"],url:["AdMarvel"]}},{STRINGIFIED_SDK:"admb",safeToInjectMraid:!0,detectionRules:{userAgent:["afma-sdk"],url:["afma-sdk"]}},{STRINGIFIED_SDK:"imbi",safeToInjectMraid:!0,detectionRules:{javascript:["InmobiObj"]}},{STRINGIFIED_SDK:"mmed",
detectionRules:{url:["mmsdk"],scriptSrc:["mmsyscache"]}},{STRINGIFIED_SDK:"mopb",safeToInjectMraid:!0,detectionRules:{javascript:["mopubFinishLoad"]}},{STRINGIFIED_SDK:"pand",detectionRules:{javascript:["PandoraApp"]}},{STRINGIFIED_SDK:"ambe",safeToInjectMraid:!0,detectionRules:{url:["amobee"]}},{STRINGIFIED_SDK:"smat",safeToInjectMraid:!0,detectionRules:{javascript:["smaato_bridge"]}},{STRINGIFIED_SDK:"afrm",safeToInjectMraid:!0,detectionRules:{javascript:["Adform"]}},{STRINGIFIED_SDK:"vrve",safeToInjectMraid:!0,
detectionRules:{javascript:["vrvsdk"]}},{STRINGIFIED_SDK:"sads",detectionRules:{javascript:["mraid.sasSendMessage"]}},{STRINGIFIED_SDK:"cnvt",detectionRules:{url:["adsx.greystripe.com/openx/www/delivery/ia.php"]}}],Mb=function(){return{decorateContextParams:function(a,c){var d=m.request("adNode"),b;if(b="adImpression"===a)b=m.request("adNode").hasAttribute("data-ias-autoplay");b&&(c.ap="false"===d.getAttribute("data-ias-autoplay")?0:1);return c}}},Nb=function(){return{listenForResult:function(){m.on("videoBlockResult",
function(a){var c=m.request("adNode"),d=!1,b="blockAd"+n.videoId;"failed"===a.action&&(d=!0);if(c&&f.isDef(c.blockAd))c.blockAd(d);else if(c&&f.isDef(c[b]))c[b](d)})}}},Ob=function(a,c){var d=!1,b=!1,e,g=function(){d||(d=!0,e=c.createViewabilityTracker("mpt",function(a){return a.isFullyInView()}))},k=function(a){if(!f.isUndef(a)){var b=-1;f.isDef(a.volume)?b=a.volume:f.isDef(a.adVolume)&&(b=a.adVolume);return b}},m=function(a){a=k(a);d||0!==a?d&&(b||0===a)&&(a={isFullyInView:function(){return!1}},
e.addState(a)):b=!0};return{init:function(){a.on({adStarted:g,adVideoStart:g,volumeChanged:function(a){m(a)},adVideoMidpoint:function(){e&&e.hasAlwaysBeen(!0)&&a.trigger("sendDt",h.DT_CODES.QUARTILE_FULLY_INVIEW)}})}}},Pb=function(a,c){var d,b,e=m.request("videoTranslator"),g=m.request("videoAutoplay"),h=a.eventData;b=e.translate(a.messageType);h=g.decorateContextParams(b,h);d=f({t:a.time-n.birthdate,tp:b,sl:c}).mixin(h);return f({indicatesPlaying:function(){return-1!=="showAd|adStarted|adVideoStart|resumeAd".indexOf(b)},
indicatesNotPlaying:function(){return-1!=="adVideoComplete|adStopped|stopAd|pauseAd".indexOf(b)},indicatesFullscreen:function(){var a=p.getWindow();return("resizeAd"===b||"initAd"===b)&&("fullscreen"===h.viewMode||h.width===a.screen.width)},indicatesNormalSize:function(){return"resizeAd"===b&&"normal"===h.viewMode},trigger:function(){m.trigger(b,h)},toString:function(){return"{"+f(d).toParams()+"}"}}).mixin(d)},Qb=function(){var a=[];return{registerEvent:function(c,d){var b=new Pb(c,d);a.push(b);
return b},toString:function(){return"{"+f({vEventCount:a.length,vEvents:"["+a.join(",")+"]"}).toParams()+"}"}}},Rb=function(){var a={AdPaused:"pauseAd",AdVolumeChange:"volumeChanged",AdPlaying:"resumeAd"};return{translate:function(c){var d=c.charAt(0).toLowerCase()+c.slice(1);c in a&&(d=a[c]);return d}}},La=function(a,c,d){var b,e,g,k=h.OUT_OF_VIEW,q=new Nb,r=new Qb,l=function(b,c){var d=c["IASid"+a],e=f.isFunction(d);if(e){var g=d.call(c,a);f.isStr(g)&&(m.provide("vc",function(){return g}),m.trigger("addOutputItem",
{output:g},"vc",{type:"impression"}))}return e},s=function(){b||(f([".integral-vid-"+a,"ias-ad","object","embed"]).findFirst(function(a,c){var d=p.getDoc().querySelectorAll(c);return b=f(f(d).toArray()).findFirst(l)}),b||__IntegralASDiagnosticCall("novidnode",{},n));return b};(function(){var b=!1,f=!1;s();c.on("hundredpct")&&c.bootstrapOn("use100v")&&(new Ob(m,d)).init();A.addEvent(p.getWindow(),"message",function(c){var e={};try{e=JSON.parse(unescape(c.data))}catch(g){e={}}e.id==a&&(c=r.registerEvent(e,
d.getCurrentLoc()),c.indicatesPlaying()?(b=!0,k=f?h.IN_VIEW:!1):c.indicatesNotPlaying()?(b=!1,k=h.OUT_OF_VIEW):c.indicatesFullscreen()?(f=!0,k=b?h.IN_VIEW:h.OUT_OF_VIEW):c.indicatesNormalSize()&&(f=!1,k=b?!1:h.OUT_OF_VIEW),c.trigger())});m.provide({videoEventsString:r,videoVersion:function(){var a,b=s();try{a=b.getVersion()}catch(c){a=-1,m.trigger("error",h.ERROR_CODES.NO_VIDEO_AD_INTERFACE)}return a},videoTranslator:function(){return e=e||new Rb},videoAutoplay:function(){return g=g||new Mb},adNode:s});
q.listenForResult()})();return{findAdNode:s,getViewStateOverride:function(){return k}}},Ma=function(a){var c={},d=a instanceof Array&&a.length;d&&(f(a).each(function(a,d){c[d.type]=d}),m.on("perfCheckpoint",function(a){var d=c[a.type];if(d)try{d.addPoint(a),d.isFinished()&&(m.trigger("addOutputItem",{output:d.toString()},h.DT_CODES.PERFORMANCE,{minDt:!0,type:h.DT_CODES.PERFORMANCE}),m.trigger("sendMinDt",h.DT_CODES.PERFORMANCE))}catch(f){}}));m.provide("perfActive",function(){return d});return{isActive:d}},
Sb=function(){function a(a){this.type=a;this.dataPoints=[]}a.prototype.baseOrdinal=0;a.prototype.sortByCode=function(){this.dataPoints.sort(function(a,d){return a.code-d.code})};a.prototype.toString=function(){var a,d,b=this,e={c:{},s:{}};this.sortByCode();f(this.dataPoints).each(function(f,h){a&&(e.s[h.code]=h.timestamp-a);d&&(e.c[h.code]=h.timestamp-d);a=h.timestamp;f===b.baseOrdinal&&(d=h.timestamp)});return f(e).toION()};a.prototype.isFinished=function(){var a=!1;f(this.dataPoints).each(function(d,
b){b.isLast&&(this.sortByCode(),a=!0)});return a};a.prototype.addPoint=function(a){this.dataPoints.push(a)};return a}(),Na=function(){function a(){}a.build=function(){var a=[],d=m.request("vc");d!==h.VIDEO_CHANNELS.VANS.AS3_ADAPTOR&&d!==h.VIDEO_CHANNELS.VANS.JS_ADAPTOR||a.push(Tb.getInstance());return a};return a}(),Tb=function(){var a=null,c=function(){var a=new Sb(h.PERF_TRACKER_TYPES.VANS.TYPE);a.isFinished=function(){return this.dataPoints.length===h.PERF_TRACKER_TYPES.VANS.COUNT};a.baseOrdinal=
0;return a};return{getInstance:function(){a||(a=c());return a}}}(),ib=function(a){var c=p.getDoc(),c=c.body||c.head||c.documentElement,d=U("/PixelB.swf","cdn"),b,e=function(){if(b||f.isFunction(d.getVersion)){var c=a.getFlashVersion();b||(b=d.getVersion(),b=b.split(" ")[1],b=b.split(",").join("."));return c+"|"+b}return"na"};c?(c.appendChild(d),m.trigger("addOutputItem",{output:e},"fx")):m.trigger("error",h.ERROR_CODES.NO_CONTAINER);return d},ab=function(){var a,c=0,d=0,b=0,e=f.debounce(function(){var c=
p.now(),e=a?(c-a)/1E3:0;1<=e&&5>=e&&b++;a=c;d++},100),g=function(){c++;e()},k=function(){m.trigger("addOutputItem",{output:{tmm:function(){return c},tma:function(){return d},sma:function(){return b}}},{type:h.DT_CODES.UNLOAD})};return{start:function(){k();A.addEvent(p.getTop().document,"mousemove",g)},isApplicable:function(a){return!v.xDomainIframe&&a.on("mmsb")}}},wa=function(){var a={},c=function(b,c){var f;b[c]=function(b,c,e){e&&(a[e]={x:b,y:c},a.ul&&a.lsr&&(f=pa().getOffDesktopResult(a.ul,a.lsr),
d(f)))}},d=function(a){try{m.trigger("addOutputItem",{output:a},"od")}catch(c){aslog.error(c),m.trigger("error",h.ERROR_CODES.OFF_DESKTOP)}};return{isApplicable:function(a,c){var d=a.on("oddet"),f=c.hasFlashEnabled(),m=c.getBrowserType()===h.BROWSERS.IE,n=c.isOnWin7(),l=c.isIEVersion(8);return!a.bootstrapOn("killFlash")&&d&&f&&m&&n&&!l},start:function(){try{Ub().setupPixels(c),setTimeout(function(){a.ul&&a.lsr||d(pa().getOffDesktopResult())},1E4)}catch(b){aslog.error(b),m.trigger("error",h.ERROR_CODES.OFF_DESKTOP)}}}},
pa=function(){var a=function(a){var d=h.NA;return a?{x:a.x-250,y:a.y-188}:{x:d,y:d}};return{getOffDesktopResult:function(c,d){c=a(c);d=a(d);return f({mc:[c.x,c.y,d.x,d.y].join("|")}).toION()}}},Ub=function(){var a="_postPosition_"+n.asid.replace(/-/g,""),c=function(c){var b=U("/PixelB.swf","cdn","name="+c+"&jsPostFn="+a,!0);c=Vb[c];b.style.width=c.WIDTH+"px";b.style.height=c.HEIGHT+"px";b.style.position="fixed";b.style.top=c.TOP+"px";b.style.left=c.LEFT+"px";return b};return{setupPixels:function(d){var b=
p.getDoc(),b=b.body||b.contentElement,e;e=p.getDoc().createElement("div");e.innerHTML='<iframe class="IAS-pixel-frame"style="width:0px !important; height: 0px !important; border-style: hidden !important"></iframe>';e=e.firstChild;b.appendChild(e);b=e.contentWindow;b.document.open().close();e=b.document.body;var f=c("ul"),h=c("lsr");e.appendChild(f);e.appendChild(h);d(b,a)}}},bb=function(){return{start:function(){var a=p.getTop().status;p.getTop().status=p.getTop().status+" ";p.getTop().status===a+
" "&&(p.getTop().status=a,m.trigger("addOutputItem",{output:1},"sb"))},isApplicable:function(a,c){return!v.xDomainIframe&&c.browserIs(h.BROWSERS.IE)&&a.on("mmsb")}}},jb=function(){var a=z.appendElement("iframe",{name:"hpif",style:"display:none"}),c=[{pieces:["jwp","la","yer"],abbr:"j"},{pieces:["flo","wpl","ayer"],abbr:"f"}],d=function(b){a.contentWindow[b.pieces.join("")]=function(){return{play:function(){m.trigger("addOutputItem",{output:b.abbr},"vh",{minDt:!0,type:h.DT_CODES.VH});m.trigger("sendMinDt",
h.DT_CODES.VH)}}}},b=5E3;(function g(){a.contentWindow?f(c).each(function(a,b){d(b)}):(b-=100,0<=b&&t.setTimeout(g,100))})()},Vb={ul:{WIDTH:3,HEIGHT:3,TOP:-3600,LEFT:-3600},lsr:{WIDTH:3,HEIGHT:3,TOP:32767,LEFT:32767}};try{kb()}catch(Wb){__IntegralASDiagnosticCall("main",Wb,n)}};try{(function(){var n=__IntegralASConfig.useFIF?window.parent:window;__IntegralASConfig.initialize(__IntegralASConfig,n,n.document)})()}catch(err$$12){__IntegralASDiagnosticCall("initialize",err$$12,__IntegralASConfig)};
